### ISSUE TITLE
COFFEE STAND / information レイアウト確認

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#1]

**Comment by niizato** [comment]
![INFO-cofee-100](https://user-images.githubusercontent.com/21334300/179647727-1a492bd6-7f26-4dca-a2fe-5c5e36fbd596.jpg)

**Comment by niizato** [comment]
<img width="994" alt="スクリーンショット 2022-07-19 11 01 00" src="https://user-images.githubusercontent.com/21334300/179647908-98746c45-29af-4f92-bead-6529c5128965.png">

**Comment by niizato** [comment]
オープン時間の書き方がわかりにくい

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179884104-2e9826a2-7d77-4ff4-9329-8f2586d4e484.png)
フォントサイズを揃えることは可能でしょうか？

**Comment by ETOmaruhiro** [comment]
レイアウト問題ないです。

**Comment by meguminiizato** [comment]
![PARKINFO_cofee-100](https://user-images.githubusercontent.com/109563863/180677029-b9a4917c-547c-4710-8469-d5a43897212a.jpg)


営業時時間分かりやすく＞
・少し文字を大きくし、OPENと加えました。
・説明文下 → ロゴ下に配置しました。

フォント揃える＞
・欧文と和文は同じサイズですが、見え方が異なるので、見え方に合わせたサイズ指定にしました。

**Comment by SuzukaEto** [comment]
フォントの件、確認いたしました。
見え方を合わせていただきありがとうございます。

**Comment by niizato** [comment]
@meguminiizato 修正確認しました。こちらクローズします。
