### ISSUE TITLE
メニュー内/PC・IPAD・SP デザイン・レイアウト確認

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#10]
メニュー内のデザインは、FIXでよろしいですか？
INFORMATION修正しています。
よろしければ進めていただきます
![MENU-ipad横-100](https://user-images.githubusercontent.com/109563863/179874357-03e32201-9a62-4455-9c53-657f4b6a5236.jpg)
![MENU-ipad縦-100](https://user-images.githubusercontent.com/109563863/179874364-4c408d32-d8a4-4539-9f42-a0217b0e1b6c.jpg)
![MENU-PC-100](https://user-images.githubusercontent.com/109563863/179874367-f412a663-8c60-4e9f-8330-f11356d970c7.jpg)
![MENU-PC-W-100](https://user-images.githubusercontent.com/109563863/179874368-00e432c9-51a0-45b1-9555-a3b0760027a4.jpg)
![MENU-SP-100](https://user-images.githubusercontent.com/109563863/179874369-655af323-c5ae-40c2-ad1f-20a4b6a9f65e.jpg)
![MENU-SP-open-100](https://user-images.githubusercontent.com/109563863/179874372-1824f671-80fc-46e2-8c36-2e67d0ba2f32.jpg)
！

**Comment by niizato** [comment]
問題ありません。issue クローズお願いします。

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
では、MENUデータ送りますね！よろしくお願いします。

**Comment by niizato** [comment]
@meguminiizato 
さっき説明のあったスマホ版のメニューについて、衞藤と話してやっぱり項目だと思う人がいるかもとなりました。
ただ、＜わたしたちについて＞　＜わたしたちについてトップ＞のように、同じ項目がPC版で並んで見えるのも微妙なので
項目に見える部分のアイコンを変えてはどうかという結論になりました。

**Comment by niizato** [comment]
<img width="431" alt="スクリーンショット 2022-07-20 11 00 53" src="https://user-images.githubusercontent.com/21334300/179879683-59e267fe-e1cb-4f53-9403-c2d3454d25a6.png">

**Comment by niizato** [comment]
例えば赤で描いた矢印みたいな。リンクがあるって分かりやすい表示が良さそう。

**Comment by SuzukaKuwabara** [comment]
@niizato @meguminiizato 
見せ方（スタイル）の変更であれば、後からでも可能ですので構築してから検討しても大丈夫です＾＾

**Comment by meguminiizato** [comment]
@niizato
確かにそっちが分かりやすそう。矢印にしてみますね。

@SuzukaKuwabara 
よかったです！

**Comment by meguminiizato** [comment]
![MENU_1-100](https://user-images.githubusercontent.com/109563863/185624974-f76e2079-4079-453f-9ae3-900ef0da9aec.jpg)
![MENU-100](https://user-images.githubusercontent.com/109563863/185624990-ab23dd06-fee1-4237-a6d8-42ee755b6893.jpg)


> 例えば赤で描いた矢印みたいな。リンクがあるって分かりやすい表示が良さそう。

こちら修正しました！
シャッター下のサブメニューは、> が多くて見づらかったのと、矢印とデザインが喧嘩してしまうので削除しました。

**Comment by niizato** [comment]
@meguminiizato 問題ありません

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
とても分かりやすくなったかと思います！
問題ありませんのでこのまま進めていただけると幸いです。
