### ISSUE TITLE
DIARYのカテゴリについて

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#12]
DIARYには一つ一つの記事に「カテゴリ」を設定することができます。
＊カテゴリは後から自由に増やすことも可能です。
＊カテゴリを設定しておくことで、特定のカテゴリの記事一覧を出すことができ便利に使えます

このサイトでどんな記事を書くのかをイメージしていただきながら、
カテゴリ名称を考えていただきたいのですが、良いでしょうか。

```
・HIROPPA BENTO
・MEDIA
・BLOG
・NEWS
```
などの分類でもいいですし

```
・HIROPPA
・OUCHI
・KOUBA
・NEWS
```
など場所によって分類しても良いと思います

ご検討いただき、お知らせください
（ご回答急ぎません）

<img width="1037" alt="DIARYカテゴリ" src="https://user-images.githubusercontent.com/109566570/180136253-cd2b5f69-d3ea-4c70-b917-836f9d482eb0.png">

**Comment by niizato** [comment]
・HIROPPA
・NEWS
・MEDIA
・MUSIC
・KITCHEN CAR
・NEW ITEM
・EN GOHAN
・OPEN-END

メモ

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。ではこれで進めますね。

**Comment by niizato** [comment]
@SuzukaKuwabara こちらちょっと待ってください〜！念の為衞藤が戻り次第確認してもらいます。

**Comment by SuzukaEto** [comment]
確認しました。
カテゴリは後からでも増やせるとのことなので、一旦新里メモの分で登録をお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato @ETOmaruhiro 
承知しました！こちらで進めます。
