### ISSUE TITLE
TOP / 動画の仕様について

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#13]
①音のON/OFFについては実装が可能でしたので既存サイトと同じ感じで進めています。音のON/OFFボタンの位置などは実装後に確認させてください。

②音がない動画を利用する場合は、音のON/OFFボタンが表示されない方が良いでしょうか？

③動画を管理画面から簡単に更新できる仕組みを作っていますが、既存サイトと同じくvimeoにアップした動画を使って表示させています。引き続きこの方法で問題ないでしょうか？（ ＝ vimeoはマルヒロさん側で管理されてますでしょうか？）

**Comment by niizato** [comment]
①音のON/OFFについては実装が可能でしたので既存サイトと同じ感じで進めています。音のON/OFFボタンの位置などは実装後に確認させてください。
＞承知しました

②音がない動画を利用する場合は、音のON/OFFボタンが表示されない方が良いでしょうか？
＞表示されない方が理想的です。

③動画を管理画面から簡単に更新できる仕組みを作っていますが、既存サイトと同じくvimeoにアップした動画を使って表示させています。引き続きこの方法で問題ないでしょうか？（ ＝ vimeoはマルヒロさん側で管理されてますでしょうか？）
＞問題ありません。
vimeoあんまり使っていませんがアカウントあります
maruhiro.syaretow@gmail.com 
maruhirohiromaru0411

**Comment by SuzukaKuwabara** [comment]
@niizato 
ありがとうございます。closeします。
