### ISSUE TITLE
PARK INFO／スマホ　デザイン・レイアウト確認

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#14]
![SP-INFO-HIROPPA-100](https://user-images.githubusercontent.com/109563863/180625219-c64b6a52-952b-4ce6-b2ef-3ee7ead281d9.jpg)
PARK INFOのスマホデザインです。
HIROPPAのページと、カテゴリタイトルのデザインイメージお送りします。
デザイン・レイアウトのご確認お願いします。

PARK INFOページ共通：
・和文カテゴリタイトルは、写真の上に右側に縦で表記
・欧文カテゴリタイトルは、ヘッダロゴの下に表記
・写真は縦2段にする
・見出しはTOPに合わせたデザイン

![SP-INFO-KOUBA-100](https://user-images.githubusercontent.com/109563863/180625222-a01efcc4-a439-4321-98e4-7d9c3ff5be7b.jpg)

![SP-INFO-STORE-100](https://user-images.githubusercontent.com/109563863/180625223-1d5c4bac-634a-4a3d-8a83-ef1137a955db.jpg)

**Comment by niizato** [comment]
@meguminiizato ヘッダーの文字と写真にかぶっているタイトルの文字サイズが変わらないのと、写真の色合いのせいであまり目立たなくなっているので、写真にかぶっているタイトルをもう少し強調したいです。

・写真を変更する
・文字サイズを調整

するなど修正お願いします。

**Comment by SuzukaEto** [comment]
デザイン確認し問題ないです。

**Comment by meguminiizato** [comment]
@SuzukaEto @niizato 

・タイトルロゴを大きくしてメリハリをつけました。
・写真をPC、スマホ両方見えやすいものに差し替えました。（ここに添付してないページも調整します）

HIROPPA＞

![SP-INFO-HIROPPA-100](https://user-images.githubusercontent.com/109563863/180917965-3095264b-c9d9-4171-804d-1bb58a127898.jpg)

ENGOHANイメージ＞

![SP-INFO-EN-100](https://user-images.githubusercontent.com/109563863/180917954-82594e68-3f31-43b8-a793-5c2d1379ec2c.jpg)

KOUBAイメージ＞

![SP-INFO-KOUBA-100](https://user-images.githubusercontent.com/109563863/180917973-cf2eb968-55a6-4d11-aac8-f468f1bc2cbb.jpg)

STOREイメージ＞

![SP-INFO-STORE-100](https://user-images.githubusercontent.com/109563863/180917977-84b9c81b-786a-4bd2-bbe4-df952e6e8b39.jpg)

**Comment by meguminiizato** [comment]
※ヘッダの上の黒い部分は、スマホで画像確認しやすくしてるもので気にしないでください！

**Comment by SuzukaEto** [comment]
前より見やすくなってますね！
大丈夫だと思います。

**Comment by SuzukaEto** [comment]
@meguminiizato 
<img width="441" alt="スクリーンショット 2022-07-26 15 47 59" src="https://user-images.githubusercontent.com/109930674/180941941-6f605c36-b329-4ab0-8f73-7468ffc1079a.png">
ちなみに注意事項の文章を改行すると変な感じになりますでしょうか？
全文が繋がっているのが少し気になり、文字の大きさを調節して改行しないなど修正可能でしょうか？

**Comment by niizato** [comment]
@meguminiizato 　レイアウト問題ありません
