### ISSUE TITLE
イベント一覧／サブメニュー（ページ内リンク）のデザインについて

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#15]
縦書きで見にくいとご指摘のあった件ですが、プロトタイプではスクロールしないとメニュー全体が見えないのが、見にくい要因かと思い、文字を小さく、カテゴリ名を短くし、ファーストビュー内に収まるようにしたものです。
カテゴリ名は、アイコンに使っている文言を入れています。
↓
<img width="1720" alt="スクリーンショット 2022-07-23 10 38 16" src="https://user-images.githubusercontent.com/109563863/180675405-39045bef-489e-4942-aa48-a5bd29a14f2c.png">

これでも見にくいという指摘があったので、横書きにしてみました。
スペースがあまり取れないので、こちらもカテゴリ名を短くしています。
カテゴリ名は、いくつかパターンを作ったのでご確認お願いします。
↓
![イベント一覧-100](https://user-images.githubusercontent.com/109563863/180675678-9cf9d546-0077-4cc3-bac8-c8dabdb77512.jpg)

スマホの表示はこのようなイメージです。
こちらも2パターンあります。
<img width="950" alt="スクリーンショット 2022-07-24 8 07 56" src="https://user-images.githubusercontent.com/109563863/180675666-334e67a5-1fc2-4ed3-8e54-122f21ca2c62.png">

ご確認よろしくお願いします。

**Comment by niizato** [comment]
<img width="885" alt="スクリーンショット 2022-07-25 11 22 52" src="https://user-images.githubusercontent.com/21334300/180681025-864e4ebc-71bd-42a7-88fb-53788c755485.png">

**Comment by niizato** [comment]
@meguminiizato メニューですが、デザイン的に縦書きがいいのですが、クリックできるかわからないので、縦書きの文字に矢印などアイコンをつけて対応お願いします。

もし横書きになる場合は一番省略した項目名が良いです。

**Comment by niizato** [comment]
<img width="903" alt="スクリーンショット 2022-07-25 11 23 37" src="https://user-images.githubusercontent.com/21334300/180681247-bfa5c7d8-4a6d-4163-88b4-8524e989b0c6.png">

**Comment by meguminiizato** [comment]
![イベント一覧-100](https://user-images.githubusercontent.com/109563863/180681298-8a86d582-7751-48f9-870f-f476110dc36c.jpg)
@niizato 
縦書きで矢印を付けました。
マウスオンで黒ベタ白抜きのイメージです。

**Comment by niizato** [comment]
@meguminiizato スマホ版はAでお願いします。Bはタイトルの上のアイコン＜開催中＞＜OUCHI＞とかぶるので

**Comment by meguminiizato** [comment]
@niizato 
<img width="1380" alt="スクリーンショット 2022-07-25 11 29 43" src="https://user-images.githubusercontent.com/109563863/180681601-de0197dc-8915-464b-a39d-e521705eb5a0.png">
サブメニューのスラッシュありバージョンです。

**Comment by niizato** [comment]
@meguminiizato スラッシュありの縦書きでお願いします。

**Comment by meguminiizato** [comment]
![イベント一覧-100](https://user-images.githubusercontent.com/109563863/180685138-c9d07879-2e54-428e-a718-9a8d03b87b06.jpg)

@SuzukaKuwabara 
デザイン・カテゴリ名はこちらで決定になりましたので、反映をお願いします。
PC版の説明文右余白は、写真からサブメニューまでの余白と合わせてください。

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
これまでのイベント　→      終了したイベント
に変更お願いします。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato @niizato 
修正点把握しました。プロトタイプに反映して、開発フェーズに進めます。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
EVENTページのプロトタイプができておりますので確認お願いいたします。（PC、SP）

**EVENT一覧**
[PC](https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/418b735e-e606-4405-b917-1bcb74332f90)　　[SP](https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/353a8a4a-db40-4d28-a855-e9ddb387abd7)

**終了したイベント一覧**
[PC](https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/c2413a4c-4550-42ac-88e2-bf4e08be9b08)　　[SP](https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/432141b6-e310-4fc1-a104-e154cf5ba088)

**イベント詳細①**
[PC](https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/9def781b-8e2c-4053-9a49-8a0261d907b9)　　[SP](https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/591a200c-a984-4943-a1ca-0e6b739b18a3)

**イベント詳細②**
[PC](https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/c7b85277-ebf3-483f-82ed-afbeb1599714)　　[SP](https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/ea4f087d-4a6e-4c82-97b7-f858ea4943e9)


気になる点はXDのコメントでも良いですし、Githubに書いてもらってもどちらでも大丈夫です。
マルヒロさん側で管理しやすい方で教えてください。

**Comment by SuzukaEto** [comment]
@SuzukaKuwabara 
XDにて順次確認いたします。
今のところEVENT一覧までコメントしてます。
