### ISSUE TITLE
ハンバーガーメニュー／ロールオーバーの色について

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#16]
4パターン送ります。
ご確認お願いします。

<img width="1659" alt="スクリーンショット 2022-07-26 14 20 28" src="https://user-images.githubusercontent.com/109563863/180929433-8c3d8148-1ab3-449f-b8c6-d89f6d0653d3.png">
![Uploading スクリーンショット 2022-07-26 14.20.41.png…](
<img width="1704" alt="スクリーンショット 2022-07-26 14 20 50" src="https://user-images.githubusercontent.com/109563863/180929451-4edba391-5767-49d8-93b9-7e7dbc393227.png">
<img width="1673" alt="スクリーンショット 2022-07-26 14 21 00" src="https://user-images.githubusercontent.com/109563863/180929454-b871fd4a-adf3-4e6c-889b-c4c25553deee.png">

**Comment by meguminiizato** [comment]
<img width="1750" alt="スクリーンショット 2022-07-26 14 20 41" src="https://user-images.githubusercontent.com/109563863/180929570-867258fd-cf4a-4771-9600-87c74fa509d1.png">

**Comment by niizato** [comment]
@meguminiizato グレーでお願いsます。色が多いので

**Comment by meguminiizato** [comment]
<img width="791" alt="スクリーンショット 2022-07-26 16 08 34" src="https://user-images.githubusercontent.com/109563863/180947130-f5fd4fa1-aefd-44e7-8bcd-bd51421c4d9d.png">

**Comment by meguminiizato** [comment]
@niizato 
ご確認お願いします！

**Comment by niizato** [comment]
@meguminiizato グレーでお願いします。
issueのクローズお願いします。
