### ISSUE TITLE
PARKINFO／レイアウト確認

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#17]
こちらChatworkで送っておりましたが、Githubに上がってなかったので再度確認です。
デザイン、レイアウトの確認お願いします。

〈確認〉
・BEEROADの素材は、オープンまでに間に合わない場合は非表示にしますか？準備中などにしますか？
・POOPの写真をお願いします。（maruhiro store／poopへリンク）

![INFO-top-100](https://user-images.githubusercontent.com/109563863/180935195-78c5e6e0-5f88-430c-87f9-cdec5a15a4d3.jpg)

**Comment by SuzukaEto** [comment]
<img width="859" alt="スクリーンショット 2022-07-26 15 22 33" src="https://user-images.githubusercontent.com/109930674/180937696-6af43ab9-5e0c-446d-a718-23be8e338f64.png">
項目と「開催中のイベント・これからのイベント」が同化していて少しわかりずらいなと思いました。2つの間にスペースを設けたりするなど何かわかりやすくする方法はありますか？

**Comment by SuzukaEto** [comment]
@niizato 
・BEEROADの素材は、オープンまでに間に合わない場合は非表示にしますか？準備中などにしますか？
こちら確認をお願いします。

POOPの写真について、来週の上山さんとの打ち合わせのときにHIROPPAに行って撮影するのはいかがでしょう？

**Comment by SuzukaEto** [comment]
レイアウト問題ないです。

**Comment by meguminiizato** [comment]
_項目と「開催中のイベント・これからのイベント」が同化していて少しわかりずらいなと思いました。2つの間にスペースを設けたりするなど何かわかりやすくする方法はありますか？_

＞確かにちょっと分かりづらかったですね。
レイアウト修正してご提案しますね！

**Comment by niizato** [comment]
<img width="923" alt="スクリーンショット 2022-07-27 10 35 41" src="https://user-images.githubusercontent.com/21334300/181141647-58c7a311-4870-4200-99e7-f3d31f176f2e.png">

**Comment by niizato** [comment]
@meguminiizato レイアウト問題ないです。

1　今週か来週撮影します。
2　KOUBAの画像差し替えます。
3　仮の画像を準備します。ちゃんと撮影したら差し替えたいです。
4　ごはん部　＞　ごはん　に変更お願いします。

**Comment by niizato** [comment]
@meguminiizato 
画像追加しています。確認したらイシュークローズお願いします。

HIROPPA OUCHI KOUBA 俯瞰
https://drive.google.com/drive/folders/1uF0ptXAZm7o3BEEAxF_ItslQJvJBtE_z?usp=sharing

BEE ROAD
https://drive.google.com/drive/folders/1a2GY1IeplFseKJ_2-B0qVoLV8-9QMVvK?usp=sharing

POOP
https://drive.google.com/drive/folders/1rKUA5EZeQv6HggtTQPlxO4x72YaM9UKp?usp=sharing

KOUBA
https://drive.google.com/drive/folders/1RF9W1W22m97Csai43_YRgn8FCy0xyBI0?usp=sharing

**Comment by meguminiizato** [comment]
![PARKINFO TOP-100](https://user-images.githubusercontent.com/109563863/187509130-91981c63-48ac-4c30-96b8-d726b1cc3f0c.jpg)

@niizato @ETOmaruhiro @SuzukaKuwabara 

お疲れさまです。
PARKINFO TOPの修正遅くなりすみません・・！
ご確認よろしくお願いします。

〈デザインについて〉
○広域マップ修正しました
○広域マップがあるので、俯瞰写真は外しました（メインイメージなし）
○POOPを削除しました
○リンクのデザイン変更しました
○TOPと同じ流れのレイアウトに

〈テキストについて〉
○施設の説明は、スプレッドシートの文章より短くしていますのでご確認お願いします。
ここは端的な説明がいいかなと思います。

○スプレッドシート記載のメインテキスト_〈徒歩2分圏内に隣接するHIROPPA ・OUCHI・ KOUBA・BEEROADがある坊辺田（ぼふた）エリアは、波佐見有田ICから車で5分、バイパス沿いにあり川棚川と田畑に囲まれた場所に位置します。
周辺には中尾山、やきもの公園、波佐見町歴史文化交流館、西の原など波佐見町で人気の観光スポットがあります。〉_
は、アクセスページの方に使用しました。
施設のご案内は、周辺エリアの説明ではない方がいいかなと思いますがいかがでしょうか？

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
修正していただきありがとうございます！デザイン問題ないです。
テキストも修正していただきありがとうございます。PARKINFOでの説明は端的なほうがいいかもしれないですね。

＞施設のご案内は、周辺エリアの説明ではない方がいいかなと思いますがいかがでしょうか？
周辺エリアの説明はアクセスページに入れるのがよさそうですね。施設のご案内テキスト作成しなおします！

**Comment by niizato** [comment]
@meguminiizato KOUBAとBEEROADは写真の差し替えお願いします。コウバは天井の画像を追加しています。ビーロードはひまわりだと期待させてしまうのでトラクターにしてください。

**Comment by niizato** [comment]
あとは大丈夫です

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro 
![PARKINFO TOP-100](https://user-images.githubusercontent.com/109563863/188520828-b2493341-e49b-42e2-b73d-5b90d078d020.jpg)
写真差し替えました！ご確認お願いします。

**Comment by niizato** [comment]
@meguminiizato これで大丈夫です
