### ISSUE TITLE
HIROPPA / information　写真差し替え

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#18]

**Comment by niizato** [comment]
EATの項目：
差し替え①＞オープンエンドのスイーツの画像　※キッチンカーのピザの画像なので
差し替え②＞えんは実際のお弁当の画像　※アルミのお弁当箱に入っている画像ので

**Comment by niizato** [comment]
@ETOmaruhiro 今週グッドデザイン用に店舗の写真を撮ってもらうそうなのでお店の写真そっちを使ってもいいかも。商品がたくさん並んでるので。メモとして残しときます。もしくは薫さんの画像。

**Comment by meguminiizato** [comment]
修正反映したHIROPPAのページです。
![PARKINFO_HIROPPA-100](https://user-images.githubusercontent.com/109563863/181412903-c337b8dd-f61b-433b-926a-81eaf43185a0.jpg)

**Comment by meguminiizato** [comment]
@ETOmaruhiro @SuzukaEto 

前回ご指摘のあった禁止事項の部分、少し書き方を変えてみたのですがいかがですか？
頭に●をつけて、※はかっこ書きにしました。

**Comment by SuzukaEto** [comment]
> @ETOmaruhiro @SuzukaEto
> 
> 前回ご指摘のあった禁止事項の部分、少し書き方を変えてみたのですがいかがですか？ 頭に●をつけて、※はかっこ書きにしました。

修正していただきありがとうございます！分かりやすくなったかと思います。
こちらで進めていただけると幸いです。

**Comment by SuzukaKuwabara** [comment]
【 施設一覧のマウスオンでのスタイルについてのご相談 】
@meguminiizato 
マウスオンで色がグレーになるスタイルですが

こちらが構築の関係で実装がちょっと難しかったです。（すみません、細かい説明は割愛させていただきます）
※MENUボタンも同じスタイルですがこちらは大丈夫です

それで、マウスオンのスタイルを
・不透明度を下げる
・ロゴが右にずれる
・> のマークが動く
など、ロゴ自体の色と形が変わらないものに変更していただくことは可能でしょうか？

![スクリーンショット 2022-09-09 14 29 32](https://user-images.githubusercontent.com/109566570/189278275-76953279-5218-4cad-9ad6-c2406ab2b6bf.png)

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
上記、施設ご案内でロゴが並んでいる箇所のマウスオンのスタイル、いかがでしょうか？
10月の検討事項にする場合、一旦「マウスオンで不透明度を下げる」で対応しておきます＾＾

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
コメント見落としていてごめんなさい！「マウスオンで不透明度を下げる」で大丈夫です。
よろしくお願いします^^
