### ISSUE TITLE
EN / information レイアウト確認

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#2]

**Comment by niizato** [comment]
![INFO-en-100](https://user-images.githubusercontent.com/21334300/179640362-1c69263b-182f-452b-b466-cdea79322a7a.jpg)

**Comment by niizato** [comment]
<img width="946" alt="スクリーンショット 2022-07-20 10 01 31" src="https://user-images.githubusercontent.com/21334300/179873259-fec70cf0-54df-4194-b225-bebfa3d8a5f0.png">

**Comment by niizato** [comment]
EN BENTO > EN GOHAN
に変更お願いします。

**Comment by niizato** [comment]
<img width="960" alt="スクリーンショット 2022-07-20 10 01 46" src="https://user-images.githubusercontent.com/21334300/179873349-a3919d05-95c1-4add-a235-73c122d0f8b8.png">

**Comment by niizato** [comment]
矢印が数字の１に見えて分かりづらいです。

**Comment by niizato** [comment]
レイアウトは問題ありません。

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179877903-89ec83bf-545b-4317-b970-85defcac536d.png)
綴りを「INFORMATION」に変更をお願いいたします。

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179878715-776a9e87-e3f4-4b0e-82fc-769005549b37.png)
綴りを「INFORMATION」に変更をお願いいたします。

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179878774-ee898fe9-c9c3-42ea-8cbd-7d5e780e4cef.png)
「EN」とイングリッシュページの「EN」が同じ表記なので、少し変えた方がいいのかなと思いました。

**Comment by ETOmaruhiro** [comment]
レイアウト問題ないです。

**Comment by niizato** [comment]
@meguminiizato 

EN > EN GOHANでお願いします。
EN の説明はFOODでお願いします。

**Comment by meguminiizato** [comment]
<img width="1219" alt="スクリーンショット 2022-07-26 12 20 05" src="https://user-images.githubusercontent.com/109563863/180915962-2fea141f-3991-40bd-b2bf-07e98d2fb6fa.png">


@ETOmaruhiro @niizato 
EN GOHAN に修正しました！
見出し1のEN GOHANはかぶってしまいますが大丈夫ですか？

スマホの時に横に長すぎるので2段組にしています。

**Comment by SuzukaEto** [comment]
修正していただきありがとうございます。
見出し1とのかぶり、2段組問題ないかと思います！

**Comment by niizato** [comment]
@meguminiizato 
見出し1について　FOODかGOHANにするのはどうですか？

**Comment by niizato** [comment]
@meguminiizato 
トップへ戻る矢印（1に見える件）も修正案お願いします。
