### ISSUE TITLE
イベントページ　プロトタイプ（XD）確認

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#20]
■イベント一覧
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/418b735e-e606-4405-b917-1bcb74332f90

■イベント詳細①
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/9def781b-8e2c-4053-9a49-8a0261d907b9

■イベント詳細②
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/c7b85277-ebf3-483f-82ed-afbeb1599714

**Comment by meguminiizato** [comment]
イベントページの文字サイズを調整しましたのでご確認お願いします。
2パターンあります。
スマホに保存して横幅を合わせて見ていただくとより分かりやすいかと思います。

A→
ページタイトル・見出し・イベント名を同じサイズ

![イベント一覧／SP-A@2x-100](https://user-images.githubusercontent.com/109563863/181152711-877b0b50-052c-4bb9-b79d-d3e5175a5d27.jpg)

サイズ説明：

<img width="543" alt="スクリーンショット 2022-07-27 12 14 18" src="https://user-images.githubusercontent.com/109563863/181153129-5f704bd3-fc52-43fc-bb93-ea477f8b370a.png">

B→
ページタイトル・ページ内リンク・見出しを同じサイズ
イベント名のみ大きく

![イベント一覧／SP-B@2x-100](https://user-images.githubusercontent.com/109563863/181152729-2b3e53b3-8a1e-4850-a74f-4f583dad3869.jpg)

サイズ説明：
<img width="571" alt="スクリーンショット 2022-07-27 12 14 27" src="https://user-images.githubusercontent.com/109563863/181153219-cfe1b0a1-45a7-42d7-8604-5c3a182feb4a.png">

**Comment by meguminiizato** [comment]
イベント一覧の中の、終了したイベント部分です。
MOREを押すのではなく、バー全体を押すようにしたイメージです。
他ページ下部に設置する、開催中のイベント・これからのイベントも共通の動きになります。
確認お願いします。

<img width="1493" alt="スクリーンショット 2022-07-27 12 44 06" src="https://user-images.githubusercontent.com/109563863/181156804-105204aa-a314-4695-837c-c6fcd227c82e.png">

マウスオンはTOPと同じ動き↓

<img width="1470" alt="スクリーンショット 2022-07-27 12 33 18" src="https://user-images.githubusercontent.com/109563863/181156815-af23a8cd-3512-4008-9baa-993516a36a6c.png">

**Comment by niizato** [comment]
@meguminiizato 確認しました。問題ありません。

**Comment by niizato** [comment]
@SuzukaKuwabara XDにコメント書き終わっています。

**Comment by SuzukaEto** [comment]
@meguminiizato 
文字サイズの調節ありがとうございます。Aでお願いします！

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
@meguminiizato 

イベントページ関係は書き込んでいただいた内容を対応しまして、
プロトタイプの修正が完了しました。


・SP/一覧ページの文字サイズ等：Aタイプで修正済みです。
https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/353a8a4a-db40-4d28-a855-e9ddb387abd7/

・PC/一覧ページの「終了したイベント」のスタイル：修正済みです
・開催中のイベント群とこれからのイベント群の間の余白修正：修正済みです
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/418b735e-e606-4405-b917-1bcb74332f90/?filter_my_comments=true

・PC/詳細ページの概要文　15pxに変更
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/9def781b-8e2c-4053-9a49-8a0261d907b9?filter_my_comments=true


こちらで開発へ進めさせていただきますね。
細かい余白等の修正などは開発後でも可能です。

**Comment by meguminiizato** [comment]
確認しました！問題ないと思います。
よろしくお願いします。

**Comment by SuzukaEto** [comment]
確認しました！問題ないです！
よろしくお願いします。
