### ISSUE TITLE
PARK MAP プロトタイプ（XD）確認

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#21]
パークマップページのプロトタイプができておりますのでご確認ください
[PC](https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/45a3f0e4-7ddf-4ba0-b6ca-e62d287f3074/?filter_my_comments=true)　[SP](https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/d7ac1276-0119-473b-9cf9-5a60815cc3e4/?filter_my_comments=true)

※モーダルウィンドウで施設詳細や植物の情報を出しますが、
疑似的に動くようになっていますのでボタンを押してみてください。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
プロトタイプのチェックについては、
XDにコメントを書いていただいていると思います。
書き終わりましたらお知らせください＾＾

**Comment by niizato** [comment]
<img width="1259" alt="スクリーンショット 2022-07-27 13 33 24" src="https://user-images.githubusercontent.com/21334300/181162264-e16e0486-d825-4e22-b6f3-687edfc216dd.png">

**Comment by niizato** [comment]
@meguminiizato 番号の位置変更可能ですか？ブルーの部分に配置したいです。

**Comment by niizato** [comment]
@SuzukaKuwabara XD内にコメント書き終わりました。

**Comment by SuzukaEto** [comment]
@SuzukaKuwabara 私もXD内にコメント書き終わりました。

**Comment by meguminiizato** [comment]
@niizato
マップに日本語は入れますか？
必要であれば、番号位置修正はその後がいいかなと思います。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
@niizato 
番号の件ですが、デザインデータからの転記時に
かなりずれてたみたいだったので一旦今の状態で調整しました。
申し訳ありません。PCもSPも修正してプロトタイプも更新しています。
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/45a3f0e4-7ddf-4ba0-b6ca-e62d287f3074/
（ページのリロードをしてご確認ください）

<img width="1194" alt="スクリーンショット 2022-07-27 14 58 00" src="https://user-images.githubusercontent.com/109566570/181172173-43d5b0a8-e213-41c8-a349-659c22fd9095.png">

**Comment by SuzukaKuwabara** [comment]
@niizato 
@meguminiizato 
14番の位置だけはデザインと関わりそうなので恵ちゃんのご指示を待とうと思いますm(_ _)m

**Comment by meguminiizato** [comment]
@niizato 
@ETOmaruhiro 

MAPスマホ版の
タイトル周りが散らかって見えるという件・・
イベントページのページ内リンクにデザインを合わせてましたが、
こんな風にボタンにするのはどうでしょうか？

![HIROPPA_MAP_SP@2x-100](https://user-images.githubusercontent.com/109563863/181400224-53e86253-c5c8-4bd5-979d-56dd8d7fd1f4.jpg)

ボタンの色は、スマホにPCも合わせたいと思います。

<img width="1831" alt="スクリーンショット 2022-07-28 10 26 41" src="https://user-images.githubusercontent.com/109563863/181400739-ee87bcf9-502d-456e-916b-530bc1fa3e5c.png">

**Comment by meguminiizato** [comment]
※ このグリーンはアイコンに使っている色です

**Comment by meguminiizato** [comment]
@niizato @SuzukaEto 

マップメニューのマウスオンのイメージです。4パターン送りますのでご検討ください！
（すみません、Cは削除したのでありません）

<img width="1723" alt="スクリーンショット 2022-07-28 11 08 27" src="https://user-images.githubusercontent.com/109563863/181405342-3bcfab1e-8d00-4c32-96b8-aa4ecbc0adf8.png">
<img width="1733" alt="スクリーンショット 2022-07-28 11 09 16" src="https://user-images.githubusercontent.com/109563863/181405364-a943b606-d1b7-4966-82c6-a55381ba01ec.png">
<img width="1760" alt="スクリーンショット 2022-07-28 11 11 36" src="https://user-images.githubusercontent.com/109563863/181405368-671f2a27-d184-4bcd-aff7-4404ce6a2f18.png">
<img width="1748" alt="スクリーンショット 2022-07-28 11 12 07" src="https://user-images.githubusercontent.com/109563863/181405371-a020e6c3-a46b-464f-b55e-8d12aa22dd55.png">

**Comment by niizato** [comment]
> @niizato @ETOmaruhiro
> 
> MAPスマホ版の タイトル周りが散らかって見えるという件・・ イベントページのページ内リンクにデザインを合わせてましたが、 こんな風にボタンにするのはどうでしょうか？
> 
> ![HIROPPA_MAP_SP@2x-100](https://user-images.githubusercontent.com/109563863/181400224-53e86253-c5c8-4bd5-979d-56dd8d7fd1f4.jpg)
> 
> ボタンの色は、スマホにPCも合わせたいと思います。
> 
> <img alt="スクリーンショット 2022-07-28 10 26 41" width="1831" src="https://user-images.githubusercontent.com/109563863/181400739-ee87bcf9-502d-456e-916b-530bc1fa3e5c.png">

ボタンで良いと思います。

**Comment by niizato** [comment]
> @niizato @SuzukaEto
> 
> マップメニューのマウスオンのイメージです。4パターン送りますのでご検討ください！ （すみません、Cは削除したのでありません）
> 
> <img alt="スクリーンショット 2022-07-28 11 08 27" width="1723" src="https://user-images.githubusercontent.com/109563863/181405342-3bcfab1e-8d00-4c32-96b8-aa4ecbc0adf8.png">
> 
> <img alt="スクリーンショット 2022-07-28 11 09 16" width="1733" src="https://user-images.githubusercontent.com/109563863/181405364-a943b606-d1b7-4966-82c6-a55381ba01ec.png">
> 
> <img alt="スクリーンショット 2022-07-28 11 11 36" width="1760" src="https://user-images.githubusercontent.com/109563863/181405368-671f2a27-d184-4bcd-aff7-4404ce6a2f18.png">
> 
> <img alt="スクリーンショット 2022-07-28 11 12 07" width="1748" src="https://user-images.githubusercontent.com/109563863/181405371-a020e6c3-a46b-464f-b55e-8d12aa22dd55.png">

@meguminiizato 一番上の黒ベタが他と統一感ありそう。統一感考えなければ白ベタ好みです。任せます。

**Comment by niizato** [comment]
> @niizato マップに日本語は入れますか？ 必要であれば、番号位置修正はその後がいいかなと思います。

日本語なしで良いです。

**Comment by meguminiizato** [comment]
マップページは他と違ってもいいかなと思うので、白ベタにしましょうか。
日本語なし了解です！

**Comment by niizato** [comment]
@meguminiizato @SuzukaKuwabara 解決したのでクローズします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@SuzukaEto 

閉じてあるのに書き込みすみません。

ご報告のみですが
MAPページのプロトタイプ完了して開発へ進めております。

以後の修正は実装後にお願いいたしますm(_ _)m

■ PC
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/45a3f0e4-7ddf-4ba0-b6ca-e62d287f3074/

■ SP
https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/d7ac1276-0119-473b-9cf9-5a60815cc3e4/
