### ISSUE TITLE
全ページ共通／ページトップへ戻る矢印

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#22]
矢印が1に見えるとのことで、修正しました！
いかがでしょうか？

<img width="1745" alt="スクリーンショット 2022-07-28 12 01 08" src="https://user-images.githubusercontent.com/109563863/181411099-86a8f374-9ee8-47f6-9271-bfd9343b7f12.png">

**Comment by niizato** [comment]
@meguminiizato 大丈夫です！クローズお願いします。
