### ISSUE TITLE
アクセス方法・駐車場・営業時間／デザイン、構成確認

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#24]
アクセス方法ページのデザインです。

・アクセス方法
・駐車場
・営業時間

こちらは情報量少なそうなので、同じページでまとめてもいいかなと思いますがいかがでしょうか？
テキストは全て仮で入れています。

![HIROPPA_ACCESS2-100](https://user-images.githubusercontent.com/109563863/183338318-563d378f-7c2d-44e2-8459-b7c7fbb6645a.jpg)

**Comment by niizato** [comment]
@meguminiizato レイアウト大丈夫です

**Comment by niizato** [comment]
@meguminiizato グーグルマップはマイマップを作って３箇所表示させる感じですか？

**Comment by ETOmaruhiro** [comment]
@meguminiizato レイアウト大丈夫です！

**Comment by ETOmaruhiro** [comment]
@meguminiizato 飛行機で長崎空港から来た人も入れたほうがいいかなと思いました。
2案あるので以下ご確認いただけると幸いです。

①「飛行機ご利用のお客様」と新しく項目を作る
・長崎空港から約1時間   
（長崎空港→バス（ハウステンボスまたは佐世保行き）→「川棚バスセンター」下車
・福岡空港から約1時間20分   
（福岡空港→高速バス（佐世保駅行き）→波佐見有田インター下車） 

②高速バスご利用のお客様に追記する

**Comment by SuzukaKuwabara** [comment]
@niizato 
> @meguminiizato グーグルマップはマイマップを作って３箇所表示させる感じですか？

構築側としては、マイマップの埋め込み可能です＾＾

**Comment by meguminiizato** [comment]
@ETOmaruhiro 
飛行機追記してみますね。
書きそびれてましたが、乗り物アイコン作ります！

**Comment by ETOmaruhiro** [comment]
@meguminiizato よろしくお願いいたします！

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro 
![HIROPPA_ACCESS2-100](https://user-images.githubusercontent.com/109563863/184796316-537fbf80-7ff9-4877-98f8-07d95b8ff9b0.jpg)

ACCESSの修正です。
飛行機のの説明と、アイコン追加しました。
ご確認お願いします！

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
修正ありがとうございます！大丈夫そうです！

**Comment by niizato** [comment]
@meguminiizato @SuzukaKuwabara 

マイマップのリンクです！
https://www.google.com/maps/d/edit?mid=1EPiThvdjQw47i63_jLTDfXbK6A-3NwY&usp=sharing
