### ISSUE TITLE
バリアフリー／デザイン・構成確認

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#25]
バリアフリーのページも仮でテキストを入れています。
下層ページでアイキャッチ画像のないものはこのフォーマットになりますので、
タイトル周りなどご確認いただけたらと思います。

r[![Uploading](url) HIROPPA_BARRIE_SP@2x-100.jpg…]()
![HIROPPA_BARRIE-100](https://user-images.githubusercontent.com/109563863/183338631-a691abcf-65f5-4ebf-a781-186ae69d97f4.jpg)

**Comment by niizato** [comment]
@meguminiizato レイアウト問題ないです。

**Comment by ETOmaruhiro** [comment]
@meguminiizato レイアウト問題ないです。
たしかにOUCHIは段差あることとか書いたほうがいいかもしれませんね。。。
記載したいことをまとめますので、一旦保留でお願いします。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
レイアウトは問題ないとのことですので、構築進めたいと思いますが良いでしょうか？
（データいただければと思います）

文章変更は後から行いますね。
