### ISSUE TITLE
PARK MAP にポイント追加

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#26]

**Comment by niizato** [comment]
<img width="2175" alt="スクリーンショット 2022-08-08 15 31 11" src="https://user-images.githubusercontent.com/21334300/183354609-cd1fc9b6-590c-4b6b-98b5-db59d4960f6c.png">

**Comment by niizato** [comment]
@meguminiizato @SuzukaKuwabara 
マップにポイントを追加したく可能でしょうか？

16　100ばいマグカップベンチ
17　せいたかのっぽせき
18　さんかくやま

**Comment by SuzukaKuwabara** [comment]
@niizato 
追加、承知しました。

@meguminiizato 
「SUNABAG」などのテキストの位置も調整しますか？
調整するのであれば、もう一回データもらいたいです＞＜
調整せずに番号を載せる場合はこちらで行います＾＾

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
テキストの位置ちょっと調整した方が良さそうなのでデータ送ります！
番号は、上から遊具→施設→設備の順にしてましたが、、並び替えるのは大変ですよね？？

@niizato @ETOmaruhiro 
マグカップ、さんかくやまはマップ上に英字いらないですか？
土偶も追加しますね。何か名前がありますか？

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 

>番号は、上から遊具→施設→設備の順にしてましたが、、並び替えるのは大変ですよね？？

差し替えるのであれば多分手間は一緒なので、大丈夫です。
画像お待ちしています。

@niizato @ETOmaruhiro 
マップのページはFIXして構築を進めているページになります。
手戻りが発生してしまいますので、差し替えがありそうであればできるだけ全部出していただけると助かりますm(_ _ )m

**Comment by meguminiizato** [comment]
![HIROPPA_website_MAP-100](https://user-images.githubusercontent.com/109563863/184814179-ee02549f-a0f7-40d8-be24-b0511e491f80.jpg)

@ETOmaruhiro @niizato 
マップの修正、項目の追加を行いました。

1〜5 変更なし。
6番以降変わっておりますので、位置や順序など気になるところがあれば、現時点でお知らせください！
また、追加がないか今一度ご確認お願いします。
マップ上にも、SEITAKANOPPOSEKIなど、英字を追加しました。

@SuzukaKuwabara 
マップにも英字デザインを追加したので、植物マップも差し替えでお願いします。
なるべく番号位置に影響しないようにしましたが、6番と13番のみ文字にかぶらないよう調整お願いします><

**Comment by ETOmaruhiro** [comment]
@meguminiizato @SuzukaKuwabara 
芝クッションを入れたいのですが、まだ間に合いそうでしょうか・・・？
芝クッションは設置場所が毎日変わるので、マップ上の空いた場所に入れていただけるといいな思っているのですが、いかがでしょうか？

ご確認のほどよろしくお願いいたします！！

**Comment by meguminiizato** [comment]
@ETOmaruhiro 
まだ大丈夫です！追加しますね。
マルヒロストアやコーヒーショップが下の方になっちゃたのですが・・大丈夫でしょうか？
まだ並びも変えれるとのことですので、順序のご確認も併せてお願いします！

**Comment by meguminiizato** [comment]
@ETOmaruhiro
<img width="1350" alt="スクリーンショット 2022-08-16 16 53 40" src="https://user-images.githubusercontent.com/109563863/184827448-abbadf9d-df2d-4cca-936e-ac5bd650da7a.png">
芝クッション、アミアミジャングル側に、とりあえず20番に 配置しています。

文字列が長くなるのがちょっと気になりますが、仕方ないですね・・^^;

**Comment by ETOmaruhiro** [comment]
@meguminiizato @SuzukaKuwabara 
まだ追加大丈夫とのことでありがとうございます！
順序は以下に変更をお願いしたいです。

①マルヒロストア
②コーヒースタンド OPEN-END
③キオスクPOOP
④みんなのトイレ
⑤授乳室
⑥エントランス
⑦どぐう
⑧ロボットの丘
⑨あみあみじゃんぐる
⑩やきものビーチ
⑪さんかくのだんだんへこみ
⑫せいたかのっぽせき
⑬100倍マグカップベンチ
⑭まるいすなバッグ
⑮さんかくやま
⑯はたけ
⑰芝クッション
⑱キッチンカーエリア
⑲ビーロード
⑳駐車場

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro 
<img width="1533" alt="スクリーンショット 2022-08-18 14 08 22" src="https://user-images.githubusercontent.com/109563863/185298540-edbccd92-fc1a-4183-97a8-dbfbd62b7643.png">

マップの修正しました！
21番にスモーキングエリアを追加しています。場所はあっていますか？
また確認ですが、授乳室の場所は左側でよかったでしょうか？

ご確認よろしくお願いします。

**Comment by niizato** [comment]
<img width="1389" alt="スクリーンショット 2022-08-18 16 25 40" src="https://user-images.githubusercontent.com/21334300/185335815-02bee0cb-b658-458f-8b14-66e4f7555e5b.png">

**Comment by niizato** [comment]
@meguminiizato 

文字の修正です

1　ロボットのおか
2　あみあみジャングル
3　100ばいマグカップベンチ
4　しばクッション
5　喫煙スペース

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
マップの修正ありがとうございます！
確認完了しました。問題ありません。

**Comment by niizato** [comment]
@meguminiizato 

名称について匡平君から変更依頼があったので一点修正お願いします。

15番　さんかくやま
↓
みどりのステージ

**Comment by meguminiizato** [comment]
<img width="1397" alt="スクリーンショット 2022-08-19 12 02 57" src="https://user-images.githubusercontent.com/109563863/185533928-4ca0ea48-1a13-4271-b5e3-fdc8befcec30.png">
<img width="1397" alt="スクリーンショット 2022-08-19 12 03 10" src="https://user-images.githubusercontent.com/109563863/185533914-f68e62c9-b80b-4427-9d56-86ea8f5c3f72.png">


マップの修正送ります。
マップデザインの英字も変更してます。

問題なければ涼香ちゃんにデータ送るので、ご連絡お待ちしてますね！

**Comment by niizato** [comment]
@meguminiizato 問題ないです。

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
問題ないようですので、データ送りますね。

1点確認ですが、パークマップの文字列のマウスオンの動きは、バー全体が白くなるイメージでしたが、
プロトタイプでは、文字が白囲みになってたので（↓）この動きであれば他と合わせて黒囲みがいいかなと思います。

@niizato どうですか？

<img width="1424" alt="スクリーンショット 2022-08-20 16 12 28" src="https://user-images.githubusercontent.com/109563863/185733822-683a9fdf-91af-4add-b979-a4d21f2e89c1.png">

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
以前のGithubのIssueで、マウスオンのところの議題が出てたときに
https://github.com/niizato/https-hiroppa.hasamiyaki.jp-/issues/21
一応やりとりを読んでプロトタイプを修正してたんですが、認識を間違ってましたね、すみません。

今いただいたデザインの通りに修正しますのでご安心ください！

**Comment by niizato** [comment]
@meguminiizato 写真は揃っています。

**Comment by niizato** [comment]
<img width="816" alt="スクリーンショット 2022-09-08 13 10 40" src="https://user-images.githubusercontent.com/21334300/189032529-35c869f4-c7bc-494d-a07d-3da69d30e454.png">

先日の台風でセンダンの木が折れてしまい、なくなってしまいました。マップからも削除が必要になるのですが修正可能ですか？

**Comment by SuzukaKuwabara** [comment]
@niizato @meguminiizato 

（開発より）まだ修正間に合います！

**Comment by SuzukaKuwabara** [comment]
こちらは台風そんなに大したことなかったんですが、九州北部はそんなに風強かったのですね。。。！

**Comment by SuzukaKuwabara** [comment]
@niizato @meguminiizato 
ちょうどいまMAPページ構築中ですので確認です。

⑤を削除し、⑥番以降の番号を変更する形で大丈夫だったでしょうか？

**Comment by niizato** [comment]
@SuzukaKuwabara 

よかったです！

⑤を削除し、⑥番以降の番号を変更する形で大丈夫だったでしょうか？

↑こちらリストも、マップ内の数字も変更になるので手間がかかりますがお願いできますか？
センダンの木が倒れて、ヒロッパの店舗の屋根も少し凹んだようです。
突風が吹いたのかも、、
対応ありがとうございます。

**Comment by SuzukaKuwabara** [comment]
@niizato 
はい、大丈夫です。修正して進めています！

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
マップの番号は、こちらで修正して送り直した方がいいですか？

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
いえ！こちらでやっているので大丈夫です＾＾

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
@meguminiizato 

すみません。確認事項があったので再度オープンしています。

画像に書いている通りですが、
パークマップの駐車場（20番）が地図上に2つあるのですが、システム上同じ番号を違う箇所に指定することが難しく・・・項目を2つにする（西駐車場、東駐車場など）ことは可能でしょうか？

![スクリーンショット 2022-09-14 18 25 19](https://user-images.githubusercontent.com/109566570/190117274-ba0e65f4-58a7-4c6b-80fc-ed7e9418ec78.png)

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
大丈夫です！西駐車場の写真がないので用意しますね！

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
では
(20)西駐車場
(21)東駐車場
(22)喫煙スペース
で進めておきますね。
