### ISSUE TITLE
PARK MAP /モーダルウィンドウに入れるテキスト量増に伴う修正

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#27]
<img width="1554" alt="スクリーンショット 2022-08-08 15 34 33" src="https://user-images.githubusercontent.com/21334300/183357054-3b721d50-99e4-4e72-8866-916137e016f1.png">

公園をぐるりと回る遊歩道から2メートルほど下がった部分には、廃品の陶器を細かく砕いた砂を敷き詰めてビーチを作っています。浅く水を貯めれば波打ち際のようなじゃぶじゃぶ池もつくれるし、夏には水をたくさん貯めて水遊びをすることができます。ビーチの壁面には竹内俊太郎による「ウツボ」が描かれてます。ビーチに水を貯めるとウツボの身体半分のみが見える状態になり、ウツボの凸が島のように見えます。

コメント

DDA
公園をぐるりと回る遊歩道から2メートルほど下がった部分には、廃品の陶器を細かく砕いた砂を敷き詰めてビーチを作っています。浅く水を貯めれば波打ち際のようなじゃぶじゃぶ池もつくれるし、夏には水をたくさん貯めて水遊びをすることができます。ビーチの壁面には竹内俊太郎による「ウツボ」が描かれてます。ビーチに水を貯めるとウツボの身体半分のみが見える状態になり、ウツボの凸が島のように見えます。面には竹内俊太郎による「ウツボ」が描かれてます。ビーチに水を貯めるとウツボの身体半分のみが見える状態になり、ウツボの凸が島のように見えます。

竹内俊太郎
公園をぐるりと回る遊歩道から2メートルほど下がった部分には、廃品の陶器を細かく砕いた砂を敷き詰めてビーチを作っています。浅く水を貯めれば波打ち際のようなじゃぶじゃぶ池もつくれるし、夏には水をたくさん貯めて水遊びをすることができます。ビーチの壁面には竹内俊太郎による「ウツボ」が描かれてます。ビーチに水を貯めるとウツボの身体半分のみが見える状態になり、ウツボの凸が島のように見えます。

馬場匡平
公園をぐるりと回る遊歩道から2メートルほど下がった部分には、廃品の陶器を細かく砕いた砂を敷き詰めてビーチを作っています。浅く水を貯めれば波打ち際のようなじゃぶじゃぶ池もつくれるし、夏には水をたくさん貯めて水遊びをすることができます。ビーチの壁面には竹内俊太郎による「ウツボ」が描かれてます。ビーチに水を貯めるとウツボの身体半分のみが見える状態になり、ウツボの凸が島のように見えます。

**Comment by niizato** [comment]
@meguminiizato @SuzukaKuwabara 

本日DDAさんと打ち合わせをして、モーダルウィンドウに入れるテキスト量が増えることになりました。
サンプルで入力していますが、関係者のコメント掲載してより深堀した内容にする為です。

どのような仕様になるかご確認お願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@meguminiizato 

文章量が増えるんですね。

ここの文章部分に見出し等が使える仕様にしていたかを
確認しますのでお待ちください。

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
文字が増える場合、枠全体が文字量に合わせて伸びる感じになりますか？
左側写真を残して、枠内で文字部分だけスクロールするとかも可能ですか？

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
お返事遅くなり申し訳ありません；；


>左側写真を残して、枠内で文字部分だけスクロールする

→可能です！

それから、見出しの利用も可能そうです。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@meguminiizato 

プロトタイプに反映してみました。
こんな感じでいかがでしょう？（文字付近にマウスを持ってくるとスクロールできます）
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/45a3f0e4-7ddf-4ba0-b6ca-e62d287f3074

**Comment by ETOmaruhiro** [comment]
@meguminiizato @meguminiizato @niizato 
![image](https://user-images.githubusercontent.com/41030665/184808094-541a89eb-3207-4694-9c43-4058e8738aae.png)
スプレッドシート「【修正】PARK MAP」にて、テキストの修正を行っております。
編集が終わり次第、報告いたします。

**Comment by meguminiizato** [comment]
> @niizato @meguminiizato
> 
> プロトタイプに反映してみました。 こんな感じでいかがでしょう？（文字付近にマウスを持ってくるとスクロールできます） https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/45a3f0e4-7ddf-4ba0-b6ca-e62d287f3074

ありがとうございます！こちらで良いと思います！

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
ではこちらで実装します!


@ETOmaruhiro 
テキストについては決定後に全て入力していきますね。
９月でも大丈夫です。

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
承知いたしました！ありがとうございます！
