### ISSUE TITLE
HIROPPA / information　プロトタイプ確認

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#28]
@niizato @SuzukaEto 

HIROPPAやOUCHIやKOUBAなど、PARK INFOのページは全て同じテンプレートを使って制作します。
プロトタイプでは、文章や写真の内容については置いておいて、
レイアウトや見え方・サイズ感の確認をお願いいたします。

また、構築の都合により各要素間の余白などを統一させたりしています。
デザインデータと全く同じになっていない部分がありますのでご了承ください。

PC
①https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/6567b264-9f9b-48c8-b4f4-c745a1616ae1/
②https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/cbcfdda2-c88c-4c0e-8831-86bdcd9d3206/

SP　（①のリンク先が間違っていたので修正しました）
①https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/f580a71c-2811-4549-81cc-68367a4a03a7/
②https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/43cd14f6-35b8-42be-994e-cbb4b3982500

**Comment by niizato** [comment]
@SuzukaKuwabara レイアウト確認しました！よろしくお願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
承知しました！

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara レイアウト確認しました！

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro
@meguminiizato  

XDプレビューへの書き込みありがとうございます。一つずつ対応していきます。

別件ですが、各施設の案内のページ名称についてなのですが
構築の都合でフッターなどメニューの名称とあわせたいです。
可能でしょうか・・・？（HIROPPA、OUCHI、KOUBAなどすべて）

可能な場合、「ヒロッパ」か「HIROPPA」のどちらかを選んでいただかないといけないのですが
どうでしょう・・・？（アルファベットの方がいい気はしてます）

※どうしてもデザイン的に難しい場合はデザイン通りに構築しますのでお知らせください


![ページ名称についての確認](https://user-images.githubusercontent.com/109566570/185009005-9d159a1f-b7b9-4d91-97e3-4004f9799ddd.jpg)

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
スマホ版のチェックはまだ終わってない感じだったでしょうか？

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
スマホ版のチェックも完了しております！

**Comment by meguminiizato** [comment]
デザインで英字を使っているので、かぶってしまうのと、日本語読みで補足的な役割で入れてたのでできれば日本語を使いたいなと思いますがいかがでしょうか？

カテゴリのタイトルになるのでしたら、文中の記載と併せた方が混乱がないでしょうか...？

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
@meguminiizato 

XDに書き込んでいただいた内容の修正が終わっておりますのでご確認ください。

**PC**
①https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/6567b264-9f9b-48c8-b4f4-c745a1616ae1/
②https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/cbcfdda2-c88c-4c0e-8831-86bdcd9d3206/

**SP**
①https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/f580a71c-2811-4549-81cc-68367a4a03a7/
②https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/43cd14f6-35b8-42be-994e-cbb4b3982500


更新するとコメントのピンが若干ずれてしまうので、
あまりにもピンの位置がずれて「どこのコメント？」ってなる部分は
一旦コメントを”解決済み”にして、新たにコメントで書き込んだりしています。
ご了承ください；


＊現在残っている検討事項　書き出しておきます
```
①メインビジュアル下：HIROPPAに営業時間を入れた方が良いか
②項目と項目の余白感
③フッター：カメラマンのクレジットの位置
④左側に画像、右側に色付きのBOX＆テキストという部分（LINEUPのところ）のレイアウト
⑤緑色の色味（XDのプレビューは実際の色と若干変わってしまうというところがあるので、実装後に検討した方がいいかもです。）
```

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
役割的には日本語がいいですよね。。

ちなみにフッターやハンバーガーメニューの項目はアルファベットの方が良かったですよね？

であれば。。
今のデザイン通りメニューでは「HIROPPA」、ページタイトルとしては「ヒロッパ」
でいきましょうか。無理ではないので＾＾

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro @SuzukaKuwabara 
<img width="1427" alt="スクリーンショット 2022-08-17 15 39 26" src="https://user-images.githubusercontent.com/109563863/185051674-af3c14ff-f2d0-437c-9c3d-f6c1cd7f2e4f.png">
試しに日本語にしてみました！
おかしくはないかなと思いますが、文中の表記が全てローマ字なのが気になりますね。

**Comment by niizato** [comment]
@meguminiizato @SuzukaKuwabara kouba hiroppa ouchは基本的にローマ字を使っているのでローマ字でお願いします。ページタイトルは縦書きなのでカタカナでも構いません

**Comment by SuzukaKuwabara** [comment]
@niizato 
ページタイトルの件についてありがとうございます。もともとのデザイン通りで進めていきますね。
（メニューなどはローマ字、ページの縦書きのタイトルは日本語）

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
画像の右側に色付きボックスとテキストが入る部分について
「テキスト量が少ない時、上に寄っているのがきになる」とのことでXDにコメントいただいていたかと思います。

ここについて恵さんと少し打ち合わせさせてもらったのですが
「上寄せのまま、文章量を調整していただいてはどうか」というお話になりました。
いかがでしょうか？

※ここは実装して全ての内容を入力後に、再度検討されても大丈夫です。
※なお、スマホの時は「最小高さを430pxにする」という設定が解除されますので何も違和感ない部分かと思います。

![画像＋テキストブロックの確認](https://user-images.githubusercontent.com/109566570/185509911-7b3d61d4-a841-447d-9621-fa2047b365ef.png)

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro 
![PARKINFO_STORE-1400-100](https://user-images.githubusercontent.com/109563863/185522089-13ca539e-b62d-475f-a81b-7de7460ad074.jpg)

プープの扱いをラインナップと同列に変更しました。

話の中で文字が入る部分の背景をグレーにするといするという案が出ましたが、グレーは写真の色と被ってしまうことが多いので、グレーブルーにしてみました。プープはポップに黄色にしてみましたがどうでしょう？
ご確認お願いします。

※ PARK INFO TOP（施設のご紹介）からプープを削除

**Comment by meguminiizato** [comment]
![PARKINFO_STORE-1400-100](https://user-images.githubusercontent.com/109563863/185762555-c53aa656-ad46-46fb-bdf5-f5ad0d549677.jpg)

@niizato 
色味調整しました。

@SuzukaKuwabara 
プープのレイアウト問題ないようですのでデータ送ります。
プロトタイプに反映お願いします。

**Comment by niizato** [comment]
@meguminiizato 色味確認しました。問題ないです。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
データ受け取りました。
プロトタイプ反映いたします。
