### ISSUE TITLE
MARUHIRO STORE 画像確認

### ISSUE THREAD

**Issue by ETOmaruhiro** [niizato/https-hiroppa.hasamiyaki.jp-#29]
![IMG_0313](https://user-images.githubusercontent.com/41030665/185270787-50f15492-cbca-4b72-9868-61263d34add4.JPG)
@meguminiizato @SuzukaKuwabara 
MARUHIRO STOREの「LINE UP」「POOP」に使用する画像について、画像のような構図で撮影していこうと思っております。
構図に問題ないか確認したいので、実際にページに当てはめていただきたいです。
よろしくお願いいたします。

**Comment by meguminiizato** [comment]
@ETOmaruhiro @niizato 
![PARKINFO_STORE-100](https://user-images.githubusercontent.com/109563863/185295789-f24010a4-259e-43c2-8fb4-558f984720f0.jpg)

写真入れてみました。トリミング違いで2箇所入れています。
写真が3:2なので、ジュースは切れてしまいました。

また、インスタから取ってきた画像を数カ所入れてみたので、構図の参考にされてください！

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro 
また、背景色が濃いと指摘があったので薄くしてみました。
先日姉が指示した色も参考で入れてますが、プロトタイプと同じくらいの明度になります。

**Comment by niizato** [comment]
> @niizato @ETOmaruhiro また、背景色が濃いと指摘があったので薄くしてみました。 先日姉が指示した色も参考で入れてますが、プロトタイプと同じくらいの明度になります。

問題ないです。
