### ISSUE TITLE
HIROPPA / information レイアウト確認

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#3]
![INFO-hiroppa-100](https://user-images.githubusercontent.com/21334300/179641628-bdc66ca4-16ea-4c01-8388-afe436d3a342.jpg)

**Comment by niizato** [comment]
EATの項目：
差し替え①＞オープンエンドのスイーツの画像
差し替え②＞えんは実際のお弁当の画像

**Comment by niizato** [comment]
<img width="1096" alt="スクリーンショット 2022-07-20 10 05 28" src="https://user-images.githubusercontent.com/21334300/179873690-882fc656-05ce-46ad-94b8-078ada1847b6.png">

**Comment by niizato** [comment]
赤枠部分改行しない

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179877334-4d298887-d3bf-4e38-bfff-9523c36d20b3.png)
綴りを「INFORMATION」に修正をお願いいたします。

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179877740-39fda5c8-690e-4048-9909-1d0975f701b7.png)
区切り線と文字の間が上下で異なるのが少し気になります。

**Comment by ETOmaruhiro** [comment]
レイアウト問題ないです。

**Comment by meguminiizato** [comment]
修正反映しました。
PARK INFOに統一しました。

**Comment by niizato** [comment]
EATの項目：
差し替え①＞オープンエンドのスイーツの画像
差し替え②＞えんは実際のお弁当の画像

マルヒロのタスクが残っているので別でissue作ります。（＃18）
@meguminiizato 修正反映されたデータをそちらにアップしてもらえると助かります。
このコメントを確認したら@meguminiizatoクローズお願いします。
