### ISSUE TITLE
共通項目／矢印・フッター修正

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#30]
（1）矢印の修正をしました。
TOPには3箇所あるのでご確認お願いします。

・EVENTスライド下
・DIALYスライド下
・カレンダー上

（2）フッターを修正しました。

・マルヒロ ロゴを一列に
・コピーライトを追加
・SNSアイコンと言語切り替えアイコンが分かりにくい　→  間に線を入れました。ナビゲーションメニューのSNSのデザインと合わせました。
・スマホフッタのHIROPPAロゴを少し小さくしました
・住所の順序を見やすく変えました。

（3）スマホに、常時表示させるページ上に戻るボタンを入れました。
デザインの途中に入れてるのでご確認ください。

〈PC版〉
![HIROPPA_TOP-100](https://user-images.githubusercontent.com/109563863/185622679-863ca6cb-4469-480b-a520-8c47c4ba18b1.jpg)

〈SP版〉
![HIROPPA_TOP_SP-100](https://user-images.githubusercontent.com/109563863/185623101-09bc971c-ece5-4c31-a73b-f85d57e08d3d.jpg)

**Comment by meguminiizato** [comment]
<img width="1440" alt="スクリーンショット 2022-08-19 22 27 53" src="https://user-images.githubusercontent.com/109563863/185629648-b36abe11-b9b7-42c9-80c3-18576cbe37a5.png">
<img width="996" alt="スクリーンショット 2022-08-19 22 30 21" src="https://user-images.githubusercontent.com/109563863/185629678-10260248-99be-4fd8-8c37-0ff132360365.png">

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
確認しました。
開発的な気になる点はありませんので決まりましたらデータお待ちしております！

**Comment by niizato** [comment]
@meguminiizato 問題ないです

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
確認しました！問題ないです。
