### ISSUE TITLE
ABOUT / プロトタイプ確認

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#31]
ABOUTページのプロトタイプを作成しましたのでご確認お願いいたします

**PC**
https://xd.adobe.com/view/232dbfd7-2cde-431c-8e16-f169dec2591d-767e/screen/ba4e4211-1f3d-40c6-ac7e-19a287eb317e/

**SP**
https://xd.adobe.com/view/ff6780a9-4907-40d8-a2d2-e3d038066cf5-aa34/screen/f5c698be-818a-44d9-9560-3aec6acd4d2f/

※フッターの修正（上に戻るボタン含む）は
反映されておりませんのでコンテンツ部分のみご確認ください。

※SPでOUCHIの表内のテキストを一部省略させていただいたところがあります。実装時は直ります。
レイアウト中心にご確認・気になる部分のご指摘ありましたら教えてください。

**Comment by niizato** [comment]
@SuzukaKuwabara 
確認しました。問題ないです！

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
遅くなってしまい申し訳ございません。
レイアウト問題ないです！

**Comment by SuzukaKuwabara** [comment]
@niizato 
@ETOmaruhiro 
お返事遅くなりすみません。こちらも開発に回していきますね。
