### ISSUE TITLE
EVENTページ：仕様についての確認

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#32]
イベント詳細ページの構築を進めていますが
一点ご相談です。

「席数」「予約」「店休日」「その他」などの
見出しの部分についても自由記入で、という仕様だったかと思いますが
構築の関係で、見出し部分は自由入力ではなく固定にさせてもらっても良いでしょうか？

![イベント詳細の仕様について](https://user-images.githubusercontent.com/109566570/188067059-a4501ae3-3463-47fe-ab40-f6106527e44d.png)

見出しも自由記入にすると、スタイルが崩れてしまうためです。
![揃えるのが難しい点](https://user-images.githubusercontent.com/109566570/188066810-5b51fcad-b63a-43dc-961b-06bcc04f4878.png)

ご了承いただけますでしょうか？

ご了承いただける場合
項目として用意しておいた方がよさそうな項目を
洗い出してもらうことは可能でしょうか？

・席数
・予約
・店休日
・その他

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
固定で大丈夫です！

・料金
・参加費

も追加で項目にいれていただけると幸いです。

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
ありがとうございます。
追加項目、承知しました！

**Comment by niizato** [comment]
@SuzukaKuwabara 
追加がまだ可能であれば

・対象年齢
・定員

※料金に大人と子供がある場合に、２箇所入れるか注意が書けるようにしてほしい

**Comment by SuzukaKuwabara** [comment]
@niizato 
追加しておきますね。

子供料金のところですが、
```
料　金　　大人1,000円 / 子ども600円
```
のように、項目一つで１行にいれるか、

```
料　金　　大人1,000円
その他　　※子ども料金は600円です
```
のように、その他の項目に注意事項を入れる対応はどうでしょう？

もちろんもう１項目追加することも可能です。

**Comment by niizato** [comment]
@SuzukaKuwabara 
料金について項目１つ、１行の対応で良さそうです！

**Comment by SuzukaKuwabara** [comment]
@niizato 
了解です！クローズしますね。
