### ISSUE TITLE
開発環境でのチェック / TOP・メニュー

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#33]
@niizato 
@ETOmaruhiro 
@meguminiizato 

開発環境での最終チェックをお願いします。
プロトタイプと異なっている部分は修正対応いたしますので教えてください。

基本的にはデザインはFIXしていますので
今月中の公開に間に合わせるためにも
大幅な構造の変更などはご遠慮いただけると幸いですm(_ _)m

**ご指摘いただいた点について**
細かい検討が必要な場合や、大幅な修正が必要な場合は、
10月にお伺いした時の議題に回させていただけると助かります。

----

**《特にこのページで見ていただきたい点》**

- カレンダーでのイベントの見え方
- カレンダーの操作性
- ハンバーガーメニューの操作性
- ヒロッパで感じてみよう〜…の文章の部分のABOUTへのリンクが文章全体に貼られているのですが、誤操作がないか
- スライダーのスピードや表示されかた
- 文字のウェイト（いま、Noto sans JPのRegularとBoldの２ウェイトで構成しています。Mediumも使った方が良さそうかどうか※日本語フォントは重たくなるのでなるべく種類が少ない方が推奨されます）
- TOPページは機能が多く若干重たくなっています。初見での表示までのスピード、ご確認ください。（２回目以降はキャッシュのおかげで表示スピードが速くなりますので、初見の際にしっかりチェックしてみてください）きになる場合はサーバーのグレードアップ等を検討された方がいいかもしれません

----

このissueでは、TOPページとメニュー画面の確認をしていただいてのフィードバックのみ
書いていただけると幸いです。他のページは別のissueを立てますね。
よろしくお願いいたします。

https://dev-hiroppa.hasamiyaki.jp/
```
ID ：　hiroppa
PASS：　test-hiroppa
```

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
確認しました！問題ありません。

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 

確認しました！下記ご確認お願いします。

TOP／PC＞

（1）ハンバーガーメニューのMENUが白ベタになっているので、抜き（透過）にしてください。

（2）ハンバーガーメニューの開き方ですが、右からディゾルプするのが気になるので、パッと表示させることはできますか？

参考：
https://takebe-happygenic.jp/
https://kawamura-museum.dic.co.jp/


（3）MENUのバツボタンをMENUの文字と同じ太さにしたいと思います。→差し替え画像送ります！

（4）MENU内のイベントカレンダーは、TOPのイベントカレンダーへリンクではなく、EVENT内のイベントカレンダーへリンクでお願いします。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
ありがとうございます。修正しますね。
メニューの開き方も修正できると思います＾＾

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
あ、それから伝え忘れてましたが
SPの時のハンバーガーメニューの閉じるボタンのところ、デザインデータでは「ACCESS」「OPEN」などのメニューが表示されている想定になっていたと思うのですが、こちら、実装が難しかったので閉じるボタンのみの配置とさせていただきました。良いでしょうか？

<img width="332" alt="デザインデータ" src="https://user-images.githubusercontent.com/109566570/190115462-ce826984-eb35-4592-88e0-daa8a9d3a2d4.png">

**Comment by meguminiizato** [comment]
> SPの時のハンバーガーメニューの閉じるボタンのところ、デザインデータでは「ACCESS」「OPEN」などのメニューが表示されている想定になっていたと思うのですが、こちら、実装が難しかったので閉じるボタンのみの配置とさせていただきました。良いでしょうか？

なるほど！そういうことですね。確認しようと思ってたところでした。
了解しました。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
よろしくお願いします。

修正、全て出てしまってから修正を始めたいと思います。
SPの修正はありますか？

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 

TOP／スマホ＞

・スマホで見ると動画が再生されません ><
・動画音量ボタンはどこに表示されますか？
・リッチメニューが出てくるタイミングについて...
動画部分がページから切れてからメニューが出てくるので、しばらくメニューが見えない状態になると思います。スマホは、ちょっと上にスクロールしたらすぐ出てくるようにできますか？

TOP／PC・スマホ共通＞
・イベントスケジュールの並びですが、上からHIROPPA→KOUBA→OUCHIとなってますが、OUCHIとKOUBAを入れ替えること可能ですか？
デザインデータでは、そのようになっていたと思います。OUCHIの方がイベントが多いので、上に持ってきたいです！
<img width="1209" alt="スクリーンショット 2022-09-15 14 57 48" src="https://user-images.githubusercontent.com/109563863/190336149-b5291881-9f47-4e03-bdd8-2befd7dafac1.png">

遅くなりすみません！あとは大丈夫です！
お手数かけますがよろしくお願いします。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
> 動画音量ボタンはどこに表示されますか？

音量調整ボタンどうしましょうね。今、非表示にしています。

既存のサイトのように左下に入っているのが自然な気はしますが、日付とお天気があるのでどこに入れるか悩ましいですね。ここは検討が必要そうな気がします。もしご了承いただければ10月の検討事項にさせていただけるとありがたいですが、どうでしょう？

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
それ以外は対応可能ですので修正に回します。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
動画が再生されない、というのがこちらでは再現できず。。。；；
キャッシュなどが影響している可能性もありますので再読み込みやシークレットモードでの閲覧でもダメかどうか、もう一度試してもらっても良いでしょうか？

それでもダメな場合、見ている環境を教えてください＞＜

・safari / Chrome ?
・使っているスマホとOSのバージョン

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
返信遅れましたが、使っている環境は、safari/i phone10/ios15.7 ですが、先ほど見たら動画再生されました！
ありがとうございました。
音量の件は、10月の会議の際で大丈夫かと思います。よろしくお願いします。

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 

メニュー・フッタ内の
SHOP → MARUHIRO STORE に変更お願いします。

<img width="1777" alt="スクリーンショット 2022-09-21 10 58 52" src="https://user-images.githubusercontent.com/109563863/191398493-f9a23062-406f-4051-a60c-5a8ebb4d6792.png">

<img width="1794" alt="スクリーンショット 2022-09-21 10 58 02" src="https://user-images.githubusercontent.com/109563863/191398487-b0c688fd-6ac8-47cb-9231-b60d40364ffb.png">

**Comment by niizato** [comment]
![image](https://user-images.githubusercontent.com/21334300/191422028-de48521a-9a5c-4f36-ba60-084eed5652e6.png)

@SuzukaKuwabara 

私のスマホではトップページがくずれてるようです。safariで開いても同様の見え方でした

**Comment by niizato** [comment]
@SuzukaKuwabara 　![image](https://user-images.githubusercontent.com/21334300/191424808-a985d7f1-82f3-49f3-8584-70a9228b03c9.png)

これぐらいのタイミングでリッチメニューが出てきたらいいなぁと感じます

**Comment by niizato** [comment]
@SuzukaKuwabara  
@meguminiizato 
![image](https://user-images.githubusercontent.com/21334300/191425224-a41882fd-cdc2-4daa-8080-9fbf6d4d4835.png)

クローズのボタンが目立つので、❌を黒のアウトラインにできますか？

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
@niizato 

> クローズのボタンが目立つので、❌を黒のアウトラインにできますか？

私もそっちがいいかなと思います。クローズボタン送りますね。

**Comment by meguminiizato** [comment]
@niizato 

<img width="588" alt="スクリーンショット 2022-09-22 13 14 27" src="https://user-images.githubusercontent.com/109563863/191657119-0bb484a8-d4ea-4384-ad08-ddeda30334a9.png">

こんな感じになります。確認お願いします。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@meguminiizato 
クローズボタン、了解しました。
SHOP→MARUHIRO STORE 変更も了解です。

@niizato 
トップページ崩れているとのことですが
ページの再読み込み（キャッシュクリア）
シークレットモードでの閲覧でもダメそうかを確かめていただき、それでもダメな場合、
閲覧環境（iphoneXXX、OSのバージョン）を教えていただいても良いでしょうか？m(_ _)m
safariもChromeも崩れたということですよね。

**Comment by SuzukaKuwabara** [comment]
@niizato 
リッチメニューのタイミングも調整します！
