### ISSUE TITLE
開発環境でのチェック / MAPページ

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#35]
@niizato
@ETOmaruhiro
@meguminiizato

開発環境での最終チェックをお願いします。
プロトタイプと異なっている部分は修正対応いたしますので教えてください。

※各施設の入力は週末に行います。見え方と操作性の確認をお願いします。

《特にこのページで見ていただきたい点》
- パークマップ、植物マップについては①と②に仮の情報が入っていますのでタップしてみてください
- SPで地図上のボタンにアニメーションつけていますが問題ないか
- 地図上の番号の位置は、パーセンテージで指定する感じなのですがPCとSPで同じ数値を指定します。そのためどうしても数字の大きさが異なることから、ややSPでずれてる感じに見えるかなと思うのですがどうでしょうか？気になるようでしたらSP基準でもう一回設定し直すことは可能です。根本的な改善は10月にさせてもらえると助かりますm(_ _)m
- SPで見た時、縦書きの「マップ」の上が隠れてしまっていますね。こちらの不備は認識済みです。修正点に加えてます。

https://dev-hiroppa.hasamiyaki.jp/info/map/
```
ID ：　hiroppa
PASS：　test-hiroppa
```

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
来週から、まずはMAPページとイベントページの更新方法をお伝えしたいなと思っています。
直接マルヒロさん側で触ってテキスト等の最終調整を行なってもらうためです。
wordpressは慣れているとは思うのですがこれまでの使い方とちょっと異なり、
ブロックエディターという記述方法で書いていきます。

HIROPPAのサイト更新担当の方はWordpressのブロックエディターを触ったことがあるでしょうか？
（それによりお伝え方法をどうするか考えようと思っています＾＾）

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
更新方法について、ご返信が遅れてしまい申し訳ございません。
HIROPPAサイト更新担当者はブロックエディターを触ったことがないと思います。
（多分Wordpressも使ったことがないかもしれないです。。。）

EC更新のときみたいに動画でお伝えいただくか、ビデオ通話などがいいのかなと思っていますがいかがでしょうか？

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
MAPページを確認しました。特に問題はないかと思います！

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
ありがとうございます。
では、更新方法についてはビデオ通話（ZOOM）にてご説明しますね。

まずはMAPページの更新方法だけ説明し
別日で施設詳細ページの更新方法だけ説明。
と、分けてご案内しようと思います。（1時間ずつくらい）
会議の様子を録画もしておくので、大丈夫かなと思います。

それ以外の更新方法についてはまた10月以降にしますね。

パソコン普通に触れる方であれば大丈夫ですよ＾＾

１回目を
9/22木曜日か、
9/27火曜日
いかがでしょう？

**Comment by niizato** [comment]
@SuzukaKuwabara 

確認しました。
SPで見たときにリストの文字が小さくて的確に押しづらいかなと思いました。男の人だったら尚更そうかも。
あと、ボタンのアニメーションについてですが、全てのボタンが同時にずっと動いているのが気になったので
「無作為（ランダム）に数個のボタンが小さく震える」とか可能ですか？
もしくは動きをゆっくりするとか、静止の感覚を開けるなど。

**Comment by niizato** [comment]
<img width="1213" alt="スクリーンショット 2022-09-21 15 33 22" src="https://user-images.githubusercontent.com/21334300/191431241-914ce571-e3fe-4197-b745-8b810999fe65.png">
@meguminiizato @SuzukaKuwabara 

テキストに修正ありました！すみません
＜サボテン＞ではなく＜観葉植物＞です。

**Comment by SuzukaKuwabara** [comment]
@niizato 
@meguminiizato 

>SPで見たときにリストの文字が小さくて的確に押しづらいかなと思いました。男の人だったら尚更そうかも。

ここですが、SPでは地図の方を触るだろうからリストは縦に長くなりすぎないようにしましょうか、
と恵ちゃんと話をして、今の大きさになりました。

とりあえず文字を大きくすることは可能ですが、10月に触りながら検討しても良いかなと思いますが、どうしましょうか・・・？

>ボタンのアニメーション

すみません、ここはできるかどうかの検討もあり、すぐにお答えや修正難しいので10月の検討事項に回させていただければと思いますm(_ _)m

**Comment by niizato** [comment]
> @niizato @meguminiizato
> 
> > SPで見たときにリストの文字が小さくて的確に押しづらいかなと思いました。男の人だったら尚更そうかも。
> 
> ここですが、SPでは地図の方を触るだろうからリストは縦に長くなりすぎないようにしましょうか、 と恵ちゃんと話をして、今の大きさになりました。
> 
> とりあえず文字を大きくすることは可能ですが、10月に触りながら検討しても良いかなと思いますが、どうしましょうか・・・？
> 
> > ボタンのアニメーション
> 
> すみません、ここはできるかどうかの検討もあり、すぐにお答えや修正難しいので10月の検討事項に回させていただければと思いますm(_ _)m

@SuzukaKuwabara どちらも10月で大丈夫です！

**Comment by niizato** [comment]
@meguminiizato @SuzukaKuwabara 

植物マップは開発環境で校正と修正を完了しています。

・植栽の設計図を見ながら追加した植物がいくつかあります。
・エリアのボタンの位置を少し修正しました。
・エリア名の名称をいくつか変更しました。
・タイトルにはカタカナと漢字を使っています。果物は基本カタカナに統一しています。
・各植物の詳細の名称はすべてカタカナのみに統一しています。

@ETOmaruhiro 
確認お願いします。

**Comment by niizato** [comment]
<img width="1255" alt="スクリーンショット 2022-09-26 15 57  1" src="https://user-images.githubusercontent.com/21334300/192212536-8ed48e15-605b-4c47-b7bf-25daea244cad.png">

@SuzukaKuwabara 
「COMMENT」の文字はどのブロックを追加すれば良いですか？

**Comment by SuzukaKuwabara** [comment]
@niizato 
上記のご質問はミーティング時にお知らせしましたので回答済みとさせていただきますね。

Wikiにもメモを残しています
https://github.com/niizato/https-hiroppa.hasamiyaki.jp-/wiki#map%E3%83%9A%E3%83%BC%E3%82%B8%E6%9B%B4%E6%96%B0%E6%96%B9%E6%B3%95
