### ISSUE TITLE
トップページの動画／TOP

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#36]
@SuzukaKuwabara @meguminiizato 

私の方で編集してみましたが使えるデータか確認お願いします。
https://drive.google.com/file/d/1b2TNnaNzT-EolSo9dJom1CvhCDfdyMJg/view?usp=sharing

**Comment by SuzukaKuwabara** [comment]
@niizato 
サイトで使うために、vimeoにアップしてURLを取る必要があるので、こちらでやってみますね。
スマホ用の動画もあるはずですが、そちらも編集可能でしょうか？

**Comment by niizato** [comment]
@SuzukaKuwabara 
同じドライブ内におそらくスマホ版だと思われる動画をアップしています。

**Comment by SuzukaKuwabara** [comment]
@niizato 
スマホ版ありました。順次差し替えしていきます。
繋ぎ目、多少プツッと切れた感じはありましたがほとんどの方が音なしで閲覧されるかと思いますので、ひとまずはこれでいいのではとおもいます。

※まだ開発環境での動画差し替えの更新作業は終わっていません。
