### ISSUE TITLE
開発環境でのチェック / DIARY

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#37]
@niizato 
@ETOmaruhiro 

DIARYページを早く書いていただけるよう、先に用意を進めています。
まだ開発終わってないのですが、先に１点確認です。

記事の詳細ページに、アイキャッチ画像を設定してもらうのですが
正方形にすると、PCの時に「大きすぎるな」と感じてしまうので
アイキャッチ画像は長方形が良いかなと思うのですが、いかがでしょうか？
(登録された画像が正方形の場合は、画像を自動で長方形にトリミングする形です）

**正方形の場合**　https://dev-hiroppa.hasamiyaki.jp/news/267/
**長方形の場合**　
![横長](https://user-images.githubusercontent.com/109566570/192640070-e39b8657-aa53-45c5-8749-7ee1fd51370a.png)

※現段階で答えが出せない場合は、一旦「長方形トリミング」で進めますので
10月の課題に回しても大丈夫です。

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
先に準備していただきありがとうございます！
正方形だと写真で画面の幅をとってしまいそうなので、長方形で問題ありません。よろしくお願いいたします！
（新里も確認済みですので、上記進めていただいて大丈夫です）

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
ありがとうございます！ではそれで進めますね。
入力よろしくお願いいたします！
