### ISSUE TITLE
開発環境でのチェック / バリアフリー

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#39]
@niizato 
@ETOmaruhiro 
@meguminiizato 

開発環境での最終チェックをお願いします。
プロトタイプと異なっている部分は修正対応いたしますので教えてください。

《特にこのページで見ていただきたい点》
- 全体的にテキストが不確定になっているようです
- 小さなお子様連れのかた・みんなのトイレについては、デザイン段階ではまだ画像もダミーの状態でしたのでご確認ください

※画像やテキストの差し替えについては、githubでご指示いただければ私の方で修正対応します。
マルヒロさん側で直接やった方が良さそうであればお知らせください＾＾

https://dev-hiroppa.hasamiyaki.jp/info/hiroppa/barrier-free/

```
ID ：　hiroppa
PASS：　test-hiroppa
```

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
バリアフリーページ確認いたしました。大丈夫だと思います！
テキスト変更と画像差し替えについて、量が多そうなのでこちらで直接したいと思います！

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
了解です！もう触っていただいて構いません。
固定ページ > バリアフリー情報
から編集してください。

**Comment by niizato** [comment]
@SuzukaKuwabara ページ問題ありません
