### ISSUE TITLE
KOUBA / information レイアウト確認

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#4]
![INFO-kouba-100](https://user-images.githubusercontent.com/21334300/179642171-d7a08e33-db94-4e37-8f31-ebafec997065.jpg)

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179876997-50dc5f22-d0ab-416e-92c0-352d09312e1d.png)
綴りを「INFORMATION」に変更をお願いいたします。

**Comment by ETOmaruhiro** [comment]
レイアウト問題ないです。

**Comment by meguminiizato** [comment]
PARK INFOに統一しました。

**Comment by niizato** [comment]
@meguminiizato 

KOUBAの画像入れています。
https://drive.google.com/drive/folders/1RF9W1W22m97Csai43_YRgn8FCy0xyBI0?usp=sharing

スプレッドシートにも記載していますが、詳細の画像は全てcomming soonでお願いします。

多分年末か年始に完成してからプロのカメラマンに撮影してもらいます。

確認したらイシューのクローズお願いします。
