### ISSUE TITLE
開発環境でのチェック / 施設のご案内

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#40]
@niizato
@ETOmaruhiro
@meguminiizato

すでに入力をしてもらっているページですが、開発が完了しておりますので最終チェックをお願いします。
プロトタイプと異なっている部分は修正対応いたしますので教えてください。

《特にこのページで見ていただきたい点》
- ページ下部の施設のロゴが並んだ部分

https://dev-hiroppa.hasamiyaki.jp/info/hiroppa/
※他施設は同じテンプレートですので省略します

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
確認しました！問題ないかと思います。

**Comment by niizato** [comment]
@SuzukaKuwabara 
問題ありません。
