### ISSUE TITLE
開発環境でのチェック / お問い合わせ

### ISSUE THREAD

**Issue by SuzukaKuwabara** [niizato/https-hiroppa.hasamiyaki.jp-#41]
@niizato
@ETOmaruhiro

開発環境での最終チェックをお願いします。
お問い合わせページは、いったん簡易的なもので良い（10月に検討）
とのことでしたので、簡易的な文章のみ記載しています。

本来はフォームにした方がいいですが、ひとまずはメールアドレスを記載するだけの形になります。

《特にこのページで見ていただきたい点》
- 問い合わせ先のメールアドレスは何か

https://dev-hiroppa.hasamiyaki.jp/contact/
※こちらのページはマルヒロさん側ですぐに編集していただくことも可能です

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
メールアドレス、こちらで入力します◎
