### ISSUE TITLE
えんごはんに項目追加

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#42]
<img width="1127" alt="スクリーンショット 2022-09-29 16 04 43" src="https://user-images.githubusercontent.com/21334300/192962885-250792d1-6bae-4802-a1cb-5e4907938d17.png">
@SuzukaKuwabara 

えんのページに「ORIGINAL GOODS」の項目を追加したいです！
タイトルは自力でできたけど、写真が複製でできなかったので対応お願いします。

**Comment by niizato** [comment]
<img width="991" alt="スクリーンショット 2022-09-29 16 13 25" src="https://user-images.githubusercontent.com/21334300/192964598-a88affc8-e0bd-45d9-bd1b-967a045c6674.png">
@SuzukaKuwabara 

ポップアップストアの部分にかき氷のメニューを入れたいのですが、オープンエンドと同じ仕様のブロックを追加してもらえますか？

**Comment by SuzukaKuwabara** [comment]
@niizato 
https://dev-hiroppa.hasamiyaki.jp/info/en/
メニューのブロック入れておきました。
順番などは変えてくださいね。

**茶色の色を変えたいときは**
茶色の部分をクリックしてから右の設定パネル > 背景 
から変更できます。３つの色から選べます。
![スクリーンショット 2022-09-29 16 40 15](https://user-images.githubusercontent.com/109566570/192970612-288d3f26-34af-4721-a641-4eb9c814c696.png)


**メニューのブロックの出し方**
![スクリーンショット 2022-09-29 16 37 32](https://user-images.githubusercontent.com/109566570/192970845-7bbfc176-da54-4b46-a008-7a384ce5288f.png)
＋マーク > 全て表示 >パターン > 画像＋説明ブロック
です。

**Comment by niizato** [comment]
@SuzukaKuwabara ありがとうございます。
