### ISSUE TITLE
画像とメニュー＆画像が並んだ時のデザイン調整／施設のご案内

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#46]
<img width="1332" alt="スクリーンショット 2022-09-30 15 05 05" src="https://user-images.githubusercontent.com/21334300/193485626-2bbc24f0-19ce-4d0c-bde9-eab70fb5470e.png">

・上段2枚と、下段メニューの間のスペースを狭くしたい
・メニューと画像の間にスペース必要じゃないか検討したい

**Comment by SuzukaKuwabara** [comment]
こちらは以前のお打ち合わせの際に解決しておりますので「解決済み」にしました
