### ISSUE TITLE
テキスト修正＆画像入れ替え／マップ

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#48]
<img width="1183" alt="スクリーンショット 2022-09-22 10 32 13" src="https://user-images.githubusercontent.com/21334300/193485907-cb8149a0-126f-4d72-b147-502d3c3d8297.png">

・「ロボットのおか」にテキスト修正
・マップのイラスト画像を最新のデザインに入れ替え

**Comment by SuzukaKuwabara** [comment]
@niizato 
ロボットのおか　の修正は完了しました

**Comment by SuzukaKuwabara** [comment]
こちら完了しておりますので「解決済み」にしました
