### ISSUE TITLE
モーダルウィンドウ内、テキストデザイン修正／マップ

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#49]
<img width="1301" alt="スクリーンショット 2022-09-22 16 03 24" src="https://user-images.githubusercontent.com/21334300/193486139-7a182ea7-101e-4581-802c-a9baed4ab348.png">

・「COMMENT」の見え方が、コメントをしたアーティスト名の見え方とあまり差がないので、色やアンダーライン、アウトラインのフォントにするなどデザインを変更したい

**Comment by niizato** [comment]
@meguminiizato 
地図の画像について駐車場の修正お願いします。
サイトに合わせて
PARKING - WEST　
PARKING - EAST　台数を45台に修正です。

**Comment by niizato** [comment]
<img width="1385" alt="スクリーンショット 2022-10-03 11 41 46" src="https://user-images.githubusercontent.com/21334300/194997618-a8eb133a-b839-4ee2-b730-d04cae3279f4.png">

**Comment by SuzukaKuwabara** [comment]
こちら完了しておりますので「解決済み」にしました
