### ISSUE TITLE
テキスト修正／トップページ

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#50]
<img width="1657" alt="スクリーンショット 2022-10-03 11 37 15" src="https://user-images.githubusercontent.com/21334300/193493381-3b89f958-e588-4bcb-8537-66f1e758d400.png">

→ オンラインストア
に修正

**Comment by SuzukaKuwabara** [comment]
@niizato 
こちら修正しています＾＾

**Comment by niizato** [comment]
@SuzukaKuwabara ありがとうございます。
