### ISSUE TITLE
ダイアリーのページデザイン／ダイアリー

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#51]
<img width="1265" alt="スクリーンショット 2022-10-03 11 58 47" src="https://user-images.githubusercontent.com/21334300/194996984-168d1457-42d6-4316-9027-752040053356.png">
右バーで最新記事や過去のアーカイブ、タグ別で選べるなどの機能
が欲しい

**Comment by niizato** [comment]
<img width="355" alt="スクリーンショット 2022-10-11 13 30 29" src="https://user-images.githubusercontent.com/21334300/194997435-484ac7a9-b55a-4980-87a8-c53f4d1e8f91.png">

**Comment by niizato** [comment]
<img width="1443" alt="スクリーンショット 2022-10-03 11 56 03" src="https://user-images.githubusercontent.com/21334300/194997867-e4e2db32-e7aa-4de2-86f9-15f6de69dedb.png">

タグをクリックして記事の選択をする機能をつけることは可能ですか？

**Comment by SuzukaKuwabara** [comment]
本日公開した修正版にて、完了しております。
