### ISSUE TITLE
動画の短縮／トップページ

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#52]
短くしました！※限定公開中です。
GCP_9秒(横)
https://vimeo.com/762517234/4d48f8c8aaプレビュー

GCP_10秒(縦)
https://vimeo.com/762517589/83bfdbbbbdプレビュー

**Comment by SuzukaKuwabara** [comment]
@niizato 
動画ありがとうございます。

**横画像について**
サイズは問題なかったのですが、動画が繰返し再生される際に黒い背景色みたいなものが映り込んでしまうようです
（録画をお送りします）こちら、改善可能でしょうか？
https://user-images.githubusercontent.com/109566570/197685282-b01a2b24-bb49-45fb-b3e9-5166c84a681f.mov

**縦画像（スマホ用）について**
立野動画の左右に黒い余白が入っているようなのですが、この余白も含めて表示してしまうので、
余白をなくして書き出していただくことは可能でしょうか？
![スクリーンショット 2022-10-25 13 44 11](https://user-images.githubusercontent.com/109566570/197685828-cbb17539-6d0d-4584-bac6-3f5991539ee5.png)

**Comment by niizato** [comment]
@SuzukaKuwabara 確認します！

**Comment by SuzukaKuwabara** [comment]
@niizato 
こちら、その後どうでしょうか？
（短いバージョンのスマホ用の画像の修正の件・PC版の動画の最後に黒い画面が入る件）

**Comment by niizato** [comment]
@SuzukaKuwabara もう一度確認しますね！

**Comment by SuzukaKuwabara** [comment]
@niizato 
よろしくお願いいたします！

---

@niizato @ETOmaruhiro 
### TOPページの読み込みスピードについて
表示までのスピードがかなり遅かったので、最もウェイトの高いメインビジュアルの動画のところで何か改善策はないかと模索しておりまして・・・  
  
それで、vimeoを使わない方法で（メディアライブラリに動画をアップする）作ってみたテストページがあるのですが、一度みていただけますでしょうか？
ただ、、問題としては音声が付けられません。

※管理者しかみれないようにしていますので、一度ログインしてから閲覧ください。  
https://hiroppa.hasamiyaki.jp/%E5%8B%95%E7%94%BB%E3%83%86%E3%82%B9%E3%83%88/  
  
実際にどのくらい早くなったのか、あまり実感がないかもしれないですが、数字的にはPCでも5.1秒→2.8秒と改善をしました（資料もあるんですが、ここでは割愛します）スマホの場合、環境によってはかなり待ち時間が多いと思うので、改善することでかなりストレスなく開けるようになるかなと思います。

・音声を省いて、より軽量化を目指すか
・音声は大切だから、今のままにするか
ご検討いただけると幸いですm(_ _  )m

※なお、現在テストページで使っている動画はvimeoからダウンロードしたものなので、若干の画質の荒れがみられるかもしれません。もし構築方法を変えてよければ、改めて動画データをいただこうと思っています。

**Comment by niizato** [comment]
@SuzukaKuwabara 

ありがとうございます！早くなる方が良いので音声を省いても良いのかなとは思います。

余白を修正したスマホ版の短縮の動画です。もう一度こちらで確認お願いします。
https://drive.google.com/file/d/1sNt_3CeKo35B29sC3D-GixvK1ZZGr2h-/view?usp=drivesdk

**Comment by SuzukaKuwabara** [comment]
@niizato 
スマホ用の動画ありがとうございます！！

ではvimeoを使わない方向で構築していきますね。
動画の圧縮についてちょっと色々と試してみたいので、短くしたバージョンのPC用の動画データもいただくことは可能でしょうか？また、マルヒロさん側で編集されたとき、何のソフト（アプリ）を使ったかわかれば教えていただいても良いでしょうか？＾＾

**Comment by niizato** [comment]
https://user-images.githubusercontent.com/21334300/212835939-b51a2a7f-a7e2-492e-81bb-71f8bd4cf2cf.mp4

**Comment by niizato** [comment]
@SuzukaKuwabara 

データはチャットワークでお送りしています。
編集ソフトは以下です。

EDIUS Pro9

**Comment by SuzukaKuwabara** [comment]
@niizato 
TOPページの動画の部分の改善、完了しました。
https://hiroppa.hasamiyaki.jp/

また、合わせてPC版で最後に黒い画面が入ってしまってたのも改善済みです。

またマニュアルには書こうと思いますが、
動画をさしかえたい時は、
①メディアライブラリに動画をアップ（この時なるべく小さく圧縮）して、その「ファイルのURL」をコピーしておきます
②トップページの編集画面へ
③メインビジュアルのブロックをクリックして、右側のパネルでURLを差し替える

という手順になります。vimeoへのアップロードはしなくて良くなりました。
<img width="1323" alt="スクリーンショット 2023-01-19 17 59 09" src="https://user-images.githubusercontent.com/109566570/213398861-1f2a88e5-c708-462c-b412-754c347fb069.png">
