### ISSUE TITLE
TOP／お知らせの出し方

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#53]
@niizato @ETOmaruhiro 
<img width="1702" alt="スクリーンショット 2022-11-14 16 21 34" src="https://user-images.githubusercontent.com/109563863/201599977-7d23cd48-64d7-4a50-a6ad-bf8876bee88f.png">
<img width="1730" alt="スクリーンショット 2022-11-14 16 24 40" src="https://user-images.githubusercontent.com/109563863/201600005-ca98aef1-bd27-4266-ac4d-69d46f9e94b6.png">

先日議題に上がったTOPページのお知らせの出し方修正しました。

問題点：
・文字量が多い時にごちゃついて見える
・複数の記事が重なった時に、スペースを取りすぎる
・ブルー文字だと目立たない

→すっきりと見えるようにまとめました。
・タイトル（太字）の後に文章をつなげます。
・リンク先で記事詳細を見れるようにします。
（@SuzukaKuwabara どこにリンクするのでしたっけ・・？）

ご確認お願いします。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
確認しました。

これを実現するとなると、
「まずDIARYでお知らせ用の記事を作成して、その記事にリンクさせる」
という感じになるのですが、改めて今考えると、
リンク先がこういう感じなので→　https://hiroppa.hasamiyaki.jp/snap/2410/
思いっきりDIARYって書いてあるし、ちょっと仰々しいかな？と思って。
（ここはあくまでも緊急お知らせのエリアなので）


なのでアコーディオンにして、開閉式にするのはどうかなと思いましたが、いかがでしょう？
（アコーディオンメニューの例）http://gokansoichiro.com/demo/accordion/

※もし、一つ一つのお知らせの内容がとても長くなりそう・DIARYのようにたくさん書きたい。という場合は「まずDIARYでお知らせ用の記事を作成して、その記事にリンクさせる」というふうにするのが良いかと思いますので、今のデザインで良いかと思います。（ただ、リンク先に「DIARY」って出てしまうことはご了承ください）

**Comment by ETOmaruhiro** [comment]
@meguminiizato @SuzukaKuwabara 
ご返信が遅れてしまい申し訳ございません。
お知らせの出し方を修正していただきありがとうございます。

情報量が多い場合、アコーディオンにするのがよさそうですね！
その場合、テキストの横に開閉できるとわかるボタン？を設置することになりますでしょうか？

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro  @meguminiizato 
システム側としては、＋マークみたいなものがあってもなくても構築はできます。
あった方が親切かなとは思います＾＾

**Comment by meguminiizato** [comment]
> @ETOmaruhiro @meguminiizato システム側としては、＋マークみたいなものがあってもなくても構築はできます。 あった方が親切かなとは思います＾＾

了解です！では、そのようにデザイン修正して送りますね^^

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
こちらデザインデータいただけてないので、お手隙の際にお願いします＾＾

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
@niizato 
@meguminiizato 

TOPページに
おしらせ機能を実装いたしました。
現在、管理者としてログインしている状態でのみ、表示しています。
ご確認ください。

問題なければ更新方法のお伝えをして、本番に公開いたしますね。
https://hiroppa.hasamiyaki.jp/

<img width="1493" alt="スクリーンショット 2022-12-20 9 27 39" src="https://user-images.githubusercontent.com/109566570/208553717-d928b2c6-1515-4170-8ecd-514f78493a42.png">

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
確認しました！実装していただきありがとうございます。
問題ございません。

**Comment by SuzukaKuwabara** [comment]
@ETOmaruhiro 
こちら実装及び使い方説明の記載も完了しました。

https://github.com/niizato/https-hiroppa.hasamiyaki.jp-/wiki/Manual#%E7%B7%8A%E6%80%A5%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
ありがとうございます！

**Comment by ETOmaruhiro** [comment]
@SuzukaKuwabara 
お尋ねです。
実際に使用してみたのですが、表示のされ方がいただいてたデザインと異なるようです。。。
文字が左よせになっていて、バナーの太さも狭いような気がします。

ご確認いただけると幸いです。よろしくお願いいたします！

**Comment by SuzukaKuwabara** [comment]
解決しました
