### ISSUE TITLE
MARUHIRO STORE / information レイアウト確認

### ISSUE THREAD

**Issue by niizato** [niizato/https-hiroppa.hasamiyaki.jp-#6]
![INFO-store-100](https://user-images.githubusercontent.com/21334300/179642862-f9a8e357-7d85-4ae2-832a-97737bc4b16c.jpg)

**Comment by niizato** [comment]
<img width="962" alt="スクリーンショット 2022-07-20 10 12 47" src="https://user-images.githubusercontent.com/21334300/179874365-aad3df51-5d60-4f4e-a7fd-25f8a1f23148.png">

**Comment by niizato** [comment]
@meguminiizato グリーンの色味が濃すぎるのが気になります

**Comment by niizato** [comment]
@meguminiizato レイアウト問題ないです。

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179876557-0380c516-b3fa-4399-8503-31601f3070f1.png)
「／」を消して「マルヒロオンラインストア」とつなげてもいいかもしれません。

**Comment by ETOmaruhiro** [comment]
![image](https://user-images.githubusercontent.com/41030665/179876670-964d0cbb-d71f-41a4-a1ca-e575d1f43789.png)
綴りを「INFORMATION」に変更をお願いいたします。

**Comment by ETOmaruhiro** [comment]
レイアウト問題ないです。

**Comment by meguminiizato** [comment]
@niizato @SuzukaEto 
修正お送りします。

・色変更
・PARK INFOに統一
・マルヒロ オンラインストアボタン

マルヒロ オンラインストアボタンは、構築上の都合で画像下に変更しています。

![PARKINFO_STORE-100](https://user-images.githubusercontent.com/109563863/180933825-b4faab18-57d1-4f87-bf0d-812726c4c9b7.jpg)

デザインOKでしたら構築の方に回したいので、写真データがあるものはできるだけ早くいただけると助かります。

**Comment by SuzukaEto** [comment]
@meguminiizato 
@niizato 
・色変更
→修正後は少し暗いトーンになったように感じたので、前の方が明るく楽しそうでいいのかなと思いました。りささんいかがでしょうか？

・PARK INFOに統一
→承知いたしました。

・マルヒロ オンラインストアボタン
→画像下に変更で承知いたしました。

写真について、まだ撮影できておらず、来週でも大丈夫でしょうか？

**Comment by niizato** [comment]
<img width="1642" alt="スクリーンショット 2022-07-26 16 17 04" src="https://user-images.githubusercontent.com/21334300/180946747-b7b0c16a-70ff-428d-8738-45672360c62c.png">

**Comment by niizato** [comment]
@meguminiizato @ETOmaruhiro 最初の色がキツすぎたのでこれくらいはどうでしょう

**Comment by SuzukaEto** [comment]
@niizato 最初のカラーより少し柔らかくなった感じがします！
@meguminiizato 　こちらのバージョンも確認することはできますか？
