### ISSUE TITLE
TOP/PC  デザイン修正（コンセプト部分・MENU・EN）

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#8]
![HIROPPA_TOP-100](https://user-images.githubusercontent.com/109563863/179649994-1304c00a-6b24-428c-8387-863b2ab06307.jpg)

・プロトタイプで指摘のあった、コンセプトの２ブロック組みを中央で1列に組みしました。
・ENの写真はこれでいいですか？
・ENの説明英文は、GOHANにしてますがどうですか？
・追従メニューのデザインは、中央に配置しているMENUアウトライン文字、カテゴリ白文字で決定でいいですか？

**Comment by niizato** [comment]
大丈夫です。

**Comment by meguminiizato** [comment]
@niizato 〈マルヒロ 確認済み〉マークは〈進行OK〉ということでいいですか？
デザイン本番に反映してもらっていいですか？

**Comment by niizato** [comment]
<img width="986" alt="スクリーンショット 2022-07-20 10 28 40" src="https://user-images.githubusercontent.com/21334300/179876026-787789e7-7381-41a4-b07b-e76c42e1fe4b.png">

**Comment by niizato** [comment]
@meguminiizato すみません、１箇所修正です。
COCKPIT OFFICE > HEAD OFFICE 
に変更お願いします。

他は大丈夫なので進行してください

**Comment by meguminiizato** [comment]
@niizato 
了解です！

@SuzukaKuwabara 
テキストの修正、コンセプトのレイアウト修正よろしくお願いします。
こちらからはENのデータ送りますね。

**Comment by SuzukaKuwabara** [comment]
対応済みです。
