### ISSUE TITLE
ABOUT レイアウト・デザイン確認

### ISSUE THREAD

**Issue by meguminiizato** [niizato/https-hiroppa.hasamiyaki.jp-#9]
![ABOUT_hiroppa-100](https://user-images.githubusercontent.com/109563863/179654517-b12969af-e787-41ca-af63-4c2aac0a2a5a.jpg)
![ABOUT_kouba-100](https://user-images.githubusercontent.com/109563863/179654543-458bd0c3-f23d-4765-88d0-241c8db2cd0f.jpg)
![ABOUT_ouchi-100](https://user-images.githubusercontent.com/109563863/179654548-34cd1a89-697e-4f66-b8e6-f90ff29c764b.jpg)

**Comment by niizato** [comment]
HIROPPA KOUBA OUCHI それぞれのバックに使ってある色についてもう少し明度が高いデザインをみたいです。

**Comment by niizato** [comment]
レイアウトに関しては私は気になるところはありません

**Comment by meguminiizato** [comment]
了解しました！

**Comment by meguminiizato** [comment]
@SuzukaKuwabara 
イベントカレンダーで色分けを、HIROPPA→グリーン、OUCHI→青、KOUBA→赤にしてましたが、
指定いただいたOUCHIの写真が青かったので、OUCHIとKOUBAの色を入れ替えました。。
イベントカレンダー＆マウスオンの色の変更は簡単にできますか？
（ABOUTの背景色決定後で大丈夫です！）

**Comment by meguminiizato** [comment]
@niizato 
波佐見焼きの紹介の後に、マルヒロ 特集ページに飛ばしてはどうかなと仮でリンクをボタンをつけています。

**Comment by niizato** [comment]
> 

了解です。

**Comment by SuzukaKuwabara** [comment]
@meguminiizato 
色の変更、承知しました。大丈夫です。

**Comment by SuzukaEto** [comment]
デザイン問題ありません。

**Comment by meguminiizato** [comment]
@niizato @SuzukaEto 
背景色の明度を上げました。確認お願いします。

![ABOUT_HIROPPA_淡色-100](https://user-images.githubusercontent.com/109563863/180918984-c98ffc26-960c-4d3d-831e-83fd057c199a.jpg)


![ABOUT_KOUBA_淡色-100](https://user-images.githubusercontent.com/109563863/180918990-eb69f698-21f3-4ce2-a2ea-4c2b8aa85c7f.jpg)


![ABOUT_OUCHI_淡色-100](https://user-images.githubusercontent.com/109563863/180918998-ca16fc20-b5e0-4ade-af33-e7285632ef4a.jpg)

**Comment by niizato** [comment]
@meguminiizato 背景色について、色のイメージが強すぎて施設のイメージまで引っ張ってしまうので背景色なしで枠にするとか、そういう代替案はないでしょうか？

**Comment by meguminiizato** [comment]
@niizato @ETOmaruhiro 

背景色なしの枠にしてみました！
枠色は、イベントのカラーに合わせています。

横幅1400px（小さめのPC）で作っていますが、
枠は、ウィンドウ幅に合わせて端まで来るイメージです。

また、建設概要などの表記部分が横2列になっていましたが、
構築や管理の面を考慮して縦１列に変更しています。

ご確認お願いします。

![ABOUT_HIROPPA2-100](https://user-images.githubusercontent.com/109563863/182986232-e4ac9d96-cfe7-4b66-ad42-b1ef478f25a4.jpg)


![ABOUT_OUCHI2-100](https://user-images.githubusercontent.com/109563863/182984305-71b04fb3-2838-42ef-8123-9869e8a982e0.jpg)


![ABOUT_KOUBA2-100](https://user-images.githubusercontent.com/109563863/182984313-3b78ade1-4c02-478c-99e0-5b7edba15886.jpg)

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
デザインに関して、修正をお願いしたい部分はございません。

**Comment by ETOmaruhiro** [comment]
@meguminiizato 
![image](https://user-images.githubusercontent.com/41030665/183007298-e49c90c1-d281-4462-94b4-8fac35e2ff56.png)
黄色線部分の修正をお願いします。

①営業時間が重複しているので削除

②設計は「DDAA 元木大輔／村井陸」に修正をお願いいたします。

**Comment by niizato** [comment]
> @niizato @ETOmaruhiro
> 
> 背景色なしの枠にしてみました！ 枠色は、イベントのカラーに合わせています。
> 
> 横幅1400px（小さめのPC）で作っていますが、 枠は、ウィンドウ幅に合わせて端まで来るイメージです。
> 
> また、建設概要などの表記部分が横2列になっていましたが、 構築や管理の面を考慮して縦１列に変更しています。
> 
> ご確認お願いします。
> 
> ![ABOUT_HIROPPA2-100](https://user-images.githubusercontent.com/109563863/182986232-e4ac9d96-cfe7-4b66-ad42-b1ef478f25a4.jpg)
> 
> ![ABOUT_OUCHI2-100](https://user-images.githubusercontent.com/109563863/182984305-71b04fb3-2838-42ef-8123-9869e8a982e0.jpg)
> 
> ![ABOUT_KOUBA2-100](https://user-images.githubusercontent.com/109563863/182984313-3b78ade1-4c02-478c-99e0-5b7edba15886.jpg)

@meguminiizato 枠のデザインでお願いします。

**Comment by meguminiizato** [comment]
了解しました。テキストの修正をして構築に回しますね！
